# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class RdmaEndpointInfo(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RdmaEndpointInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRdmaEndpointInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # RdmaEndpointInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RdmaEndpointInfo
    def MrInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dlslime.fbs.RemoteMr import RemoteMr

            obj = RemoteMr()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RdmaEndpointInfo
    def MrInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RdmaEndpointInfo
    def MrInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RdmaEndpointInfo
    def IoInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dlslime.fbs.RdmaInfo import RdmaInfo

            obj = RdmaInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RdmaEndpointInfo
    def IoInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RdmaEndpointInfo
    def IoInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # RdmaEndpointInfo
    def MsgMetaInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dlslime.fbs.RdmaInfo import RdmaInfo

            obj = RdmaInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RdmaEndpointInfo
    def MsgMetaInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RdmaEndpointInfo
    def MsgMetaInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RdmaEndpointInfo
    def MsgDataInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from dlslime.fbs.RdmaInfo import RdmaInfo

            obj = RdmaInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RdmaEndpointInfo
    def MsgDataInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RdmaEndpointInfo
    def MsgDataInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RdmaEndpointInfo
    def RemoteMetaBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from dlslime.fbs.RemoteMr import RemoteMr

            obj = RemoteMr()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def RdmaEndpointInfoStart(builder):
    builder.StartObject(5)


def Start(builder):
    return RdmaEndpointInfoStart(builder)


def RdmaEndpointInfoAddMrInfo(builder, mrInfo):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(mrInfo), 0
    )


def AddMrInfo(builder, mrInfo):
    return RdmaEndpointInfoAddMrInfo(builder, mrInfo)


def RdmaEndpointInfoStartMrInfoVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartMrInfoVector(builder, numElems):
    return RdmaEndpointInfoStartMrInfoVector(builder, numElems)


def RdmaEndpointInfoAddIoInfo(builder, ioInfo):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(ioInfo), 0
    )


def AddIoInfo(builder, ioInfo):
    return RdmaEndpointInfoAddIoInfo(builder, ioInfo)


def RdmaEndpointInfoStartIoInfoVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartIoInfoVector(builder, numElems):
    return RdmaEndpointInfoStartIoInfoVector(builder, numElems)


def RdmaEndpointInfoAddMsgMetaInfo(builder, msgMetaInfo):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(msgMetaInfo), 0
    )


def AddMsgMetaInfo(builder, msgMetaInfo):
    return RdmaEndpointInfoAddMsgMetaInfo(builder, msgMetaInfo)


def RdmaEndpointInfoStartMsgMetaInfoVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartMsgMetaInfoVector(builder, numElems):
    return RdmaEndpointInfoStartMsgMetaInfoVector(builder, numElems)


def RdmaEndpointInfoAddMsgDataInfo(builder, msgDataInfo):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(msgDataInfo), 0
    )


def AddMsgDataInfo(builder, msgDataInfo):
    return RdmaEndpointInfoAddMsgDataInfo(builder, msgDataInfo)


def RdmaEndpointInfoStartMsgDataInfoVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartMsgDataInfoVector(builder, numElems):
    return RdmaEndpointInfoStartMsgDataInfoVector(builder, numElems)


def RdmaEndpointInfoAddRemoteMetaBase(builder, remoteMetaBase):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(remoteMetaBase), 0
    )


def AddRemoteMetaBase(builder, remoteMetaBase):
    return RdmaEndpointInfoAddRemoteMetaBase(builder, remoteMetaBase)


def RdmaEndpointInfoEnd(builder):
    return builder.EndObject()


def End(builder):
    return RdmaEndpointInfoEnd(builder)
