# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class RdmaInfo(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RdmaInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRdmaInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # RdmaInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RdmaInfo
    def Qpn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return 0

    # RdmaInfo
    def Gid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from dlslime.fbs.IbvGid import IbvGid

            obj = IbvGid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RdmaInfo
    def Gidx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # RdmaInfo
    def Lid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0

    # RdmaInfo
    def Psn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # RdmaInfo
    def Mtu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0


def RdmaInfoStart(builder):
    builder.StartObject(6)


def Start(builder):
    return RdmaInfoStart(builder)


def RdmaInfoAddQpn(builder, qpn):
    builder.PrependUint32Slot(0, qpn, 0)


def AddQpn(builder, qpn):
    return RdmaInfoAddQpn(builder, qpn)


def RdmaInfoAddGid(builder, gid):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(gid), 0)


def AddGid(builder, gid):
    return RdmaInfoAddGid(builder, gid)


def RdmaInfoAddGidx(builder, gidx):
    builder.PrependInt64Slot(2, gidx, 0)


def AddGidx(builder, gidx):
    return RdmaInfoAddGidx(builder, gidx)


def RdmaInfoAddLid(builder, lid):
    builder.PrependUint16Slot(3, lid, 0)


def AddLid(builder, lid):
    return RdmaInfoAddLid(builder, lid)


def RdmaInfoAddPsn(builder, psn):
    builder.PrependUint64Slot(4, psn, 0)


def AddPsn(builder, psn):
    return RdmaInfoAddPsn(builder, psn)


def RdmaInfoAddMtu(builder, mtu):
    builder.PrependUint64Slot(5, mtu, 0)


def AddMtu(builder, mtu):
    return RdmaInfoAddMtu(builder, mtu)


def RdmaInfoEnd(builder):
    return builder.EndObject()


def End(builder):
    return RdmaInfoEnd(builder)
