# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class RemoteMr(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoteMr()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRemoteMr(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # RemoteMr
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoteMr
    def Addr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # RemoteMr
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # RemoteMr
    def Rkey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return 0

    # RemoteMr
    def MrKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0


def RemoteMrStart(builder):
    builder.StartObject(4)


def Start(builder):
    return RemoteMrStart(builder)


def RemoteMrAddAddr(builder, addr):
    builder.PrependUint64Slot(0, addr, 0)


def AddAddr(builder, addr):
    return RemoteMrAddAddr(builder, addr)


def RemoteMrAddLength(builder, length):
    builder.PrependUint64Slot(1, length, 0)


def AddLength(builder, length):
    return RemoteMrAddLength(builder, length)


def RemoteMrAddRkey(builder, rkey):
    builder.PrependUint32Slot(2, rkey, 0)


def AddRkey(builder, rkey):
    return RemoteMrAddRkey(builder, rkey)


def RemoteMrAddMrKey(builder, mrKey):
    builder.PrependUint64Slot(3, mrKey, 0)


def AddMrKey(builder, mrKey):
    return RemoteMrAddMrKey(builder, mrKey)


def RemoteMrEnd(builder):
    return builder.EndObject()


def End(builder):
    return RemoteMrEnd(builder)
