import os
from nanodeploy import LLM
from nanovllm import SamplingParams
from transformers import AutoTokenizer


def main():
    path = os.path.expanduser("/models/models--Qwen--Qwen3-8B/snapshots/2069b3fae1114555f3c020c81410e51fa0f656f2")
    tokenizer = AutoTokenizer.from_pretrained(path)
    llm = LLM(
        path,
        enforce_eager=True,
        tensor_parallel_size=2,
        expert_parallel_size=1,
        data_parallel_size=4
    )

    sampling_params = SamplingParams(temperature=0.1, max_tokens=1, ignore_eos=True)
    prompts = [
        "explain quantum computing in simple terms" * 1024,
        "how to bake a chocolate cake from scratch" * 1024,
        "what are the benefits of meditation" * 1024,
        "list 5 famous scientists and their contributions" * 1024,
        "describe the process of photosynthesis" * 1024,
        "how does a refrigerator work" * 1024,
        "what is the history of the internet" * 1024,
        "suggest 3 ways to reduce plastic waste" * 1024,
        # "explain the concept of artificial intelligence",
        # "what are the main causes of climate change",
        # "how to learn a new language effectively",
        # "describe the plot of your favorite book",
        # "what is the role of mitochondria in cells",
        # "how does gravity affect time",
        # "list 5 healthy breakfast options",
        # "explain the difference between weather and climate",
        # "what are the symptoms of a common cold",
        # "how to start a vegetable garden",
        # "describe the structure of an atom",
        # "what is the importance of bees to ecosystems",
        # "how does a battery produce electricity",
        # "list 3 famous paintings and their artists",
        # "explain the water cycle",
        # "what are the benefits of reading regularly",
        # "how to fix a leaky faucet",
        # "describe the function of the heart",
        # "what is the difference between a virus and a bacteria",
        # "suggest 5 fun outdoor activities for kids",
        # "explain the concept of supply and demand",
        # "what causes earthquakes",
        # "how to improve public speaking skills",
        # "list 5 countries and their capital cities",
        # "describe the process of making wine",
        # "what is the role of the United Nations",
        # "how does a camera capture images",
        # "what are the effects of sleep deprivation",
        # "suggest 3 ways to save money",
        # "explain the theory of evolution",
        # "what is the history of the Olympic Games",
        # "how to play the basic chords on a guitar",
        # "list 5 types of clouds and their characteristics",
        # "describe the function of the kidneys",
        # "what is the difference between a hurricane and a tornado",
        # "how does a microwave oven work",
        # "what are the benefits of exercise",
        # "suggest 5 classic movies everyone should watch",
        # "explain the concept of democracy",
        # "what causes thunder and lightning",
        # "how to write a resume",
        # "list 5 elements and their symbols",
        # "describe the process of brewing coffee",
        # "what is the role of a CPU in a computer",
        # "how does a parachute work",
        # "what are the symptoms of stress",
        # "suggest 3 ways to improve air quality",
        # "explain the concept of relativity",
        # "what is the history of chocolate",
        # "how to tie a tie",
        # "list 5 famous landmarks and their locations",
        # "describe the function of the lungs",
        # "what is the difference between a comet and an asteroid",
        # "how does a credit card work",
        # "what are the benefits of eating fruits and vegetables",
        # "suggest 5 board games for family night",
        # "explain the concept of gravity",
        # "what causes a lunar eclipse",
        # "how to learn to code for beginners",
        # "list 5 major world religions",
        # "describe the process of making bread",
        # "what is the role of DNA in genetics",
        # "how does a smartphone camera work",
        # "what are the effects of smoking",
        # "suggest 3 ways to conserve water",
        # "explain the concept of inertia",
        # "what is the history of jazz music",
        # "how to plan a budget trip",
        # "list 5 types of birds and their habitats",
        # "describe the function of the brain",
        # "what is the difference between a lake and a river",
        # "how does a wind turbine generate electricity",
        # "what are the benefits of yoga",
        # "suggest 5 science experiments for kids",
        # "explain the concept of光合作用 (photosynthesis in Chinese)",
        # "what causes the seasons",
        # "how to negotiate a salary",
        # "list 5 famous poets and their works",
        # "describe the process of recycling paper",
        # "what is the role of the liver in the body",
        # "how does a television display images",
        # "what are the symptoms of dehydration",
        # "suggest 3 ways to reduce energy consumption",
        # "explain the concept of blockchain",
        # "what is the history of the printing press",
        # "how to do a push-up correctly",
        # "list 5 chemical elements and their uses",
        # "describe the function of the immune system",
        # "what is the difference between a laptop and a tablet",
        # "how does a hot air balloon work",
        # "what are the benefits of drinking water",
        # "suggest 5 books for personal growth",
        # "explain the concept of magnetism",
        # "what causes a rainbow",
        # "how to start a blog",
        # "list 5 ancient civilizations and their contributions",
        # "describe the process of making cheese",
        # "what is the role of the moon in tides",
        # "how does a GPS system work",
        # "what are the effects of obesity",
        # "suggest 3 ways to improve mental health",
        # "explain the concept of evaporation",
        # "what is the history of the bicycle",
        # "how to change a flat tire",
        # "list 5 types of flowers and their meanings",
        # "describe the function of the stomach",
        # "what is the difference between a star and a planet",
        # "how does a hair dryer work",
        # "what are the benefits of getting enough sleep",
        # "suggest 5 outdoor activities for adults",
        # "explain the concept of electricity",
        # "what causes a tsunami",
        # "how to cook perfect rice",
        # "list 5 programming languages and their uses",
        # "describe the process of making glass",
        # "what is the role of the atmosphere in protecting Earth",
        # "how does a clock keep time",
        # "what are the symptoms of allergies",
        # "suggest 3 ways to improve soil quality",
        # "explain the concept of momentum",
        # "what is the history of the automobile",
        # "how to play chess basics",
        # "list 5 famous composers and their works",
        # "describe the function of the skin",
        # "what is the difference between a forest and a jungle",
        # "how does a vacuum cleaner work",
        # "what are the benefits of volunteering",
        # "suggest 5 documentaries worth watching",
        # "explain the concept of pH levels",
        # "what causes auroras (northern lights)",
        # "how to write a cover letter",
        # "list 5 types of fish and their habitats",
        # "describe the process of making soap",
        # "what is the role of plants in the carbon cycle",
        # "how does a radar system work",
        # "what are the effects of air pollution",
        # "suggest 3 ways to promote biodiversity",
        # "explain the concept of buoyancy",
        # "what is the history of the Internet",
        # "how to do a handstand",
        # "list 5 countries with the highest population",
        # "describe the function of the pancreas",
        # "what is the difference between a virus and a vaccine",
        # "how does a washing machine work",
        # "what are the benefits of a balanced diet",
        # "suggest 5 puzzles to improve brain function",
        # "explain the concept of photosynthesis",
        # "what causes a solar eclipse",
        # "how to learn a musical instrument",
        # "list 5 major mountain ranges and their locations",
        # "describe the process of making beer",
        # "what is the role of enzymes in digestion",
        # "how does a drone fly",
        # "what are the effects of noise pollution",
        # "suggest 3 ways to reduce food waste",
        # "explain the concept of acceleration",
        # "what is the history of the telephone",
        # "how to plant a tree",
        # "list 5 types of reptiles and their characteristics",
        # "describe the function of the eyes",
        # "what is the difference between a hurricane and a cyclone",
        # "how does a calculator work",
        # "what are the benefits of reading to children",
        # "suggest 5 card games for a group",
        # "explain the concept of radiation",
        # "what causes fog",
        # "how to create a social media strategy",
        # "list 5 famous scientists from the 20th century",
        # "describe the process of making pottery",
        # "what is the role of the ozone layer",
        # "how does a speaker produce sound",
        # "what are the symptoms of the flu",
        # "suggest 3 ways to improve communication skills",
        # "explain the concept of fermentation",
        # "what is the history of paper",
        # "how to do a backbend",
        # "list 5 types of rocks and their formation",
        # "describe the function of the ears",
        # "what is the difference between a website and a web application",
        # "how does a sprinkler system work",
        # "what are the benefits of spending time in nature",
        # "suggest 5 movies based on true stories",
        # "explain the concept of gravity",
        # "what causes a drought",
        # "how to make homemade pasta",
        # "list 5 programming frameworks and their uses",
        # "describe the process of making candles",
        # "what is the role of the Sun in the solar system",
        # "how does a remote control work",
        # "what are the effects of deforestation",
        # "suggest 3 ways to support local businesses",
        # "explain the concept of wavelength",
        # "what is the history of photography",
        # "how to tie a knot for camping",
        # "list 5 types of insects and their roles in ecosystems",
        # "describe the function of the bones",
        # "what is the difference between a lake and an ocean",
        # "how does a toaster work",
        # "what are the benefits of learning a musical instrument",
        # "suggest 5 board games for adults",
        # "explain the concept of chemical reactions",
        # "what causes a blizzard",
        # "how to create a personal budget",
        # "list 5 famous female scientists and their contributions",
        # "describe the process of making wine",
        # "what is the role of the heart in the circulatory system",
        # "how does a helicopter fly",
        # "what are the effects of alcohol consumption",
        # "suggest 3 ways to reduce traffic congestion",
        # "explain the concept of velocity",
        # "what is the history of the light bulb",
        # "how to grow herbs indoors",
        # "list 5 types of mammals and their characteristics",
        # "describe the function of the muscles",
        # "what is the difference between a tornado and a twister",
        # "how does a dishwasher work",
        # "what are the benefits of practicing gratitude",
        # "suggest 5 science fiction books",
        # "explain the concept of evaporation",
        # "what causes a hailstorm",
        # "how to write a short story",
        # "list 5 major rivers in the world",
        # "describe the process of making chocolate",
        # "what is the role of the nervous system",
        # "how does a satellite work",
        # "what are the effects of overfishing",
        # "suggest 3 ways to improve public transportation",
        # "explain the concept of force",
        # "what is the history of the computer",
        # "how to do a cartwheel",
        # "list 5 types of clouds and their associated weather",
        # "describe the function of the nose",
        # "what is the difference between a router and a modem",
        # "how does a fan work",
        # "what are the benefits of a morning routine",
        # "suggest 5 documentaries about nature",
        # "explain the concept of photosynthesis",
        # "what causes a volcanic eruption",
        # "how to make a fruit salad",
        # "list 5 programming languages for beginners",
        # "describe the process of making bread",
        # "what is the role of plants in the ecosystem",
        # "how does a watch work",
        # "what are the effects of plastic pollution on marine life",
        # "suggest 3 ways to conserve energy at home",
        # "explain the concept of density",
        # "what is the history of the wheel",
        # "how to build a birdhouse",
        # "list 5 types of flowers and their growing conditions",
        # "describe the function of the mouth",
        # "what is the difference between a star and a constellation",
        # "how does a hair straightener work",
        # "what are the benefits of reading fiction",
        # "suggest 5 party games for kids",
        # "explain the concept of electricity",
        # "what causes a thunderstorm",
        # "how to learn a new skill quickly",
        # "list 5 famous artists and their art styles",
        # "describe the process of making ice cream",
        # "what is the role of the kidneys in the body",
        # "how does a camera lens work",
        # "what are the effects of poor posture",
        # "suggest 3 ways to improve soil fertility",
        # "explain the concept of reflection",
        # "what is the history of the piano",
        # "how to change a light bulb safely",
        # "list 5 types of trees and their uses",
        # "describe the function of the blood",
        # "what is the difference between a computer and a smartphone",
        # "how does a humidifier work",
        # "what are the benefits of drinking green tea",
        # "suggest 5 books for children",
        # "explain the concept of refraction",
        # "what causes a heatwave",
        # "how to write an essay",
        # "list 5 major deserts in the world",
        # "describe the process of making jam",
        # "what is the role of the atmosphere in climate",
        # "how does a barcode scanner work",
        # "what are the effects of global warming",
        # "suggest 3 ways to reduce carbon footprint",
        # "explain the concept of mass",
        # "what is the history of the internet",
        # "how to plant a vegetable garden",
        # "list 5 types of amphibians and their characteristics",
        # "describe the function of the lungs",
        # "what is the difference between a hurricane and a typhoon",
        # "how does a blender work",
        # "what are the benefits of meditation for children",
        # "suggest 5 strategy games",
        # "explain the concept of photosynthesis",
        # "what causes a dust storm",
        # "how to make a smoothie",
        # "list 5 programming languages for data science",
        # "describe the process of making pottery",
        # "what is the role of the liver in digestion",
        # "how does a smartwatch work",
        # "what are the effects of air pollution on health",
        # "suggest 3 ways to improve water quality",
        # "explain the concept of energy",
        # "what is the history of the automobile",
        # "how to do a yoga pose for beginners",
        # "list 5 types of birds of prey",
        # "describe the function of the skin",
        # "what is the difference between a laptop and a desktop computer",
        # "how does a vacuum sealer work",
        # "what are the benefits of learning a second language",
        # "suggest 5 movies about space",
        # "explain the concept of magnetism",
        # "what causes a snowstorm",
        # "how to create a resume",
        # "list 5 famous inventors and their inventions",
        # "describe the process of making cheese",
        # "what is the role of the moon in the tides",
        # "how does a GPS device work",
        # "what are the effects of sleep deprivation on children",
        # "suggest 3 ways to promote renewable energy",
        # "explain the concept of acceleration",
        # "what is the history of the telephone",
        # "how to grow tomatoes",
        # "list 5 types of reptiles and their habitats",
        # "describe the function of the eyes",
        # "what is the difference between a virus and a bacterium",
        # "how does a washing machine clean clothes",
        # "what are the benefits of a plant-based diet",
        # "suggest 5 puzzle games for smartphones",
        # "explain the concept of evaporation",
        # "what causes a landslide",
        # "how to write a poem",
        # "list 5 major mountain peaks in the world",
        # "describe the process of making beer",
        # "what is the role of the immune system",
        # "how does a drone camera work",
        # "what are the effects of noise pollution on health",
        # "suggest 3 ways to reduce food waste at home",
        # "explain the concept of force and motion",
        # "what is the history of the light bulb",
        # "how to build a campfire safely",
        # "list 5 types of insects and their benefits",
        # "describe the function of the bones and muscles",
        # "what is the difference between a lake and a pond",
        # "how does a toaster toast bread",
        # "what are the benefits of reading for brain health",
        # "suggest 5 board games for teenagers",
        # "explain the concept of chemical bonds",
        # "what causes a cyclone",
        # "how to create a budget",
        # "list 5 famous scientists and their discoveries",
        # "describe the process of making chocolate",
        # "what is the role of the Sun in climate",
        # "how does a remote control car work",
        # "what are the effects of deforestation on wildlife",
        # "suggest 3 ways to improve public parks",
        # "explain the concept of wavelength and frequency",
        # "what is the history of photography",
        # "how to tie a bowline knot",
        # "list 5 types of rocks and their uses",
        # "describe the function of the ears and hearing",
        # "what is the difference between a website and a blog",
        # "how does a sprinkler system water lawns",
        # "what are the benefits of spending time outdoors",
        # "suggest 5 documentaries about science",
        # "explain the concept of gravity and its effects",
        # "what causes a drought",
        # "how to make homemade pizza",
        # "list 5 programming frameworks for web development",
        # "describe the process of making candles",
        # "what is the role of the ozone layer in protecting Earth",
        # "how does a speaker produce different sounds",
        # "what are the effects of air pollution on plants",
        # "suggest 3 ways to support local farmers",
        # "explain the concept of velocity and speed",
        # "what is the history of the computer mouse",
        # "how to grow herbs in pots",
        # "list 5 types of mammals and their behaviors",
        # "describe the function of the heart and circulatory system",
        # "what is the difference between a tornado and a waterspout",
        # "how does a dishwasher clean dishes",
        # "what are the benefits of practicing mindfulness",
        # "suggest 5 science fiction movies",
        # "explain the concept of evaporation and condensation",
        # "what causes a hailstorm",
        # "how to write a book review",
        # "list 5 major rivers in Asia",
        # "describe the process of making wine from grapes",
        # "what is the role of the nervous system in the body",
        # "how does a satellite transmit signals",
        # "what are the effects of overfishing on oceans",
        # "suggest 3 ways to improve public transportation",
        # "explain the concept of force and pressure",
        # "what is the history of the internet browser",
        # "how to do a push-up properly",
        # "list 5 types of clouds and their formation",
        # "describe the function of the nose and smell",
        # "what is the difference between a router and a switch",
        # "how does a fan circulate air",
        # "what are the benefits of a consistent sleep schedule",
        # "suggest 5 nature documentaries",
        # "explain the concept of photosynthesis and respiration",
        # "what causes a volcanic eruption",
        # "how to make a fruit smoothie bowl",
        # "list 5 programming languages for mobile app development",
        # "describe the process of making bread from scratch",
        # "what is the role of plants in the carbon cycle",
        # "how does a wristwatch keep time",
        # "what are the effects of plastic pollution on land",
        # "suggest 3 ways to conserve water in the garden",
        # "explain the concept of density and buoyancy",
        # "what is the history of the wheel and axle",
        # "how to build a simple bird feeder",
        # "list 5 types of flowers and their symbolic meanings",
        # "describe the function of the mouth and digestion",
        # "what is the difference between a star and a planet",
        # "how does a hair dryer dry hair",
        # "what are the benefits of reading non-fiction books",
        # "suggest 5 party games for adults",
        # "explain the concept of electricity and magnetism",
        # "what causes a thunderstorm",
        # "how to learn a new language in 30 days",
        # "list 5 famous artists and their most famous works",
        # "describe the process of making ice cream at home",
        # "what is the role of the kidneys in filtering blood",
        # "how does a camera focus on objects",
        # "what are the effects of poor posture on the spine",
        # "suggest 3 ways to improve soil health for gardening",
        # "explain the concept of reflection and refraction of light",
        # "what is the history of the piano and its development",
        # "how to change a light bulb in a high ceiling",
        # "list 5 types of trees and their environmental benefits",
        # "describe the function of blood cells",
        # "what is the difference between a computer virus and malware",
        # "how does a humidifier add moisture to air",
        # "what are the benefits of drinking herbal tea",
        # "suggest 5 children's books that teach values",
        # "explain the concept of refraction and its applications",
        # "what causes a heatwave",
        # "how to write a research paper",
        # "list 5 major deserts in Africa",
        # "describe the process of making jam from fruit",
        # "what is the role of the atmosphere in weather patterns",
        # "how does a barcode scanner read barcodes",
        # "what are the effects of global warming on polar ice",
        # "suggest 3 ways to reduce personal carbon footprint",
        # "explain the concept of mass and weight",
        # "what is the history of social media",
        # "how to plant a flower garden",
        # "list 5 types of amphibians and their life cycles",
        # "describe the function of the lungs in respiration",
        # "what is the difference between a hurricane and a cyclone",
        # "how does a blender blend ingredients",
        # "what are the benefits of meditation for stress relief",
        # "suggest 5 strategy board games",
        # "explain the concept of photosynthesis in plants",
        # "what causes a dust storm",
        # "how to make a healthy smoothie",
        # "list 5 programming languages for artificial intelligence",
        # "describe the process of making pottery on a wheel",
        # "what is the role of the liver in detoxification",
        # "how does a smartwatch track fitness",
        # "what are the effects of air pollution on climate",
        # "suggest 3 ways to improve water quality in rivers",
        # "explain the concept of energy and its forms",
        # "what is the history of electric cars",
        # "how to do a basic yoga stretch",
        # "list 5 types of birds of prey and their prey",
        # "describe the function of the skin in protection",
        # "what is the difference between a laptop and a tablet",
        # "how does a vacuum sealer preserve food",
        # "what are the benefits of learning a second language for the brain",
        # "suggest 5 movies about space exploration",
        # "explain the concept of magnetism and its uses",
        # "what causes a snowstorm",
        # "how to create a professional resume",
        # "list 5 famous inventors and their most important inventions",
        # "describe the process of making cheese from milk",
        # "what is the role of the moon in Earth's tides",
        # "how does a GPS navigation system work",
        # "what are the effects of sleep deprivation on memory",
        # "suggest 3 ways to promote solar energy use",
        # "explain the concept of acceleration and deceleration",
        # "what is the history of the telephone and its evolution",
        # "how to grow tomatoes in containers",
        # "list 5 types of reptiles and their diets",
        # "describe the function of the eyes in vision",
        # "what is the difference between a virus and a vaccine",
        # "how does a washing machine remove stains",
        # "what are the benefits of a plant-based diet for the environment",
        # "suggest 5 puzzle games for mental stimulation",
        # "explain the concept of evaporation and the water cycle",
        # "what causes a landslide",
        # "how to write a creative poem",
        # "list 5 major mountain peaks in the Himalayas",
        # "describe the process of making beer from barley",
        # "what is the role of the immune system in fighting diseases",
        # "how does a drone's camera capture video",
        # "what are the effects of noise pollution on wildlife",
        # "suggest 3 ways to reduce food waste in restaurants",
        # "explain the concept of force, mass, and acceleration",
        # "what is the history of the incandescent light bulb",
        # "how to build a safe campfire in the wilderness",
        # "list 5 types of insects and their roles in pollination",
        # "describe the function of the skeletal and muscular systems",
        # "what is the difference between a lake and a reservoir",
        # "how does a toaster's heating element work",
        # "what are the benefits of reading for vocabulary development",
        # "suggest 5 board games for family gatherings",
        # "explain the concept of chemical reactions and bonds",
        # "what causes a cyclone in the Indian Ocean",
        # "how to create a personal monthly budget",
        # "list 5 famous scientists and their contributions to medicine",
        # "describe the process of making chocolate from cacao beans",
        # "what is the role of the Sun in photosynthesis",
        # "how does a remote control car move",
        # "what are the effects of deforestation on climate",
        # "suggest 3 ways to improve public park facilities",
        # "explain the concept of wavelength, frequency, and energy",
        # "what is the history of digital photography",
        # "how to tie a secure knot for boating",
        # "list 5 types of rocks and their geological significance",
        # "describe the function of the ears in hearing and balance",
        # "what is the difference between a website and a web application",
        # "how does an automatic sprinkler system work",
        # "what are the benefits of spending time in nature for mental health",
        # "suggest 5 documentaries about environmental issues",
        # "explain the concept of gravity and its role in the solar system",
        # "what causes a drought in desert regions",
        # "how to make homemade pizza from scratch",
        # "list 5 programming frameworks for backend development",
        # "describe the process of making scented candles",
        # "what is the role of the ozone layer in UV protection",
        # "how does a speaker produce different frequencies",
        # "what are the effects of air pollution on buildings",
        # "suggest 3 ways to support local food producers",
        # "explain the concept of velocity, speed, and direction",
        # "what is the history of the computer keyboard",
        # "how to grow herbs indoors year-round",
        # "list 5 types of mammals and their conservation status",
        # "describe the function of the heart in pumping blood",
        # "what is the difference between a tornado and a dust devil",
        # "how does a dishwasher's heating element work",
        # "what are the benefits of practicing mindfulness meditation",
        # "suggest 5 science fiction novels",
        # "explain the concept of evaporation, condensation, and precipitation",
        # "what causes a hailstorm in summer",
        # "how to write a comprehensive book review",
        # "list 5 major rivers in North America",
        # "describe the process of making wine from start to finish",
        # "what is the role of the nervous system in movement",
        # "how does a communication satellite work",
        # "what are the effects of overfishing on coral reefs",
        # "suggest 3 ways to improve public transportation efficiency",
        # "explain the concept of force, pressure, and area",
        # "what is the history of the first web browser",
        # "how to do a proper push-up for beginners",
        # "list 5 types of clouds and their altitude ranges",
        # "describe the function of the nose in breathing and smell",
        # "what is the difference between a router and a firewall",
        # "how does a ceiling fan circulate air in a room",
        # "what are the benefits of a consistent bedtime routine",
        # "suggest 5 nature documentaries by David Attenborough",
        # "explain the concept of photosynthesis and cellular respiration",
        # "what causes a volcanic eruption in the Pacific Ring of Fire",
        # "how to make a nutritious fruit smoothie bowl",
        # "list 5 programming languages for game development",
        # "describe the process of making sourdough bread",
        # "what is the role of plants in oxygen production",
        # "how does a mechanical wristwatch work",
        # "what are the effects of plastic pollution on wildlife",
        # "suggest 3 ways to conserve water in commercial buildings",
        # "explain the concept of density and its effect on floating",
        # "what is the history of the wheel in ancient civilizations",
        # "how to build a DIY bird feeder from recycled materials",
        # "list 5 types of flowers and their optimal growing conditions",
        # "describe the function of the mouth in eating and speaking",
        # "what is the difference between a star and a galaxy",
        # "how does a hair dryer's heating element work",
        # "what are the benefits of reading non-fiction for knowledge",
        # "suggest 5 party games for a birthday celebration",
        # "explain the concept of electromagnetism",
        # "what causes a severe thunderstorm",
        # "how to learn a new language using mobile apps",
        # "list 5 famous artists and their artistic movements",
        # "describe the process of making homemade ice cream with an ice cream maker",
        # "what is the role of the kidneys in maintaining homeostasis",
        # "how does a camera's autofocus system work",
        # "what are the effects of poor posture on breathing",
        # "suggest 3 ways to improve soil fertility organically",
        # "explain the concept of light reflection in mirrors",
        # "what is the history of the piano from harpsichord",
        # "how to change a light bulb in a chandelier",
        # "list 5 types of trees and their wood uses",
        # "describe the function of red and white blood cells",
        # "what is the difference between a computer virus and a worm",
        # "how does a humidifier prevent dry air",
        # "what are the benefits of drinking green tea for metabolism",
        # "suggest 5 children's books about friendship",
        # "explain the concept of light refraction in lenses",
        # "what causes a heatwave in urban areas",
        # "how to write a research paper outline",
        # "list 5 major deserts in Australia",
        # "describe the process of making strawberry jam",
        # "what is the role of the atmosphere in temperature regulation",
        # "how does a barcode scanner decode information",
        # "what are the effects of global warming on sea levels",
        # "suggest 3 ways to reduce carbon emissions from transportation",
        # "explain the concept of mass versus weight",
        # "what is the history of Facebook and social media",
        # "how to plant a vegetable garden in raised beds",
        # "list 5 types of amphibians and their unique features",
        # "describe the function of the lungs in gas exchange",
        # "what is the difference between a hurricane and a typhoon",
        # "how does a blender's motor work",
        # "what are the benefits of meditation for anxiety",
        # "suggest 5 strategy games for two players",
        # "explain the concept of photosynthesis in simple terms",
        # "what causes a dust storm in desert regions",
        # "how to make a healthy green smoothie",
        # "list 5 programming languages for data visualization",
        # "describe the process of making hand-built pottery",
        # "what is the role of the liver in metabolism",
        # "how does a smartwatch monitor heart rate",
        # "what are the effects of air pollution on visibility",
        # "suggest 3 ways to improve water quality in lakes",
        # "explain the concept of energy transformation",
        # "what is the history of Tesla and electric cars",
        # "how to do a basic yoga sun salutation",
        # "list 5 types of birds of prey and their habitats",
        # "describe the function of the skin in temperature regulation",
        # "what is the difference between a laptop and a netbook",
        # "how does a vacuum sealer remove air",
        # "what are the benefits of bilingualism in children",
        # "suggest 5 movies about Mars exploration",
        # "explain the concept of magnetic fields",
        # "what causes a blizzard in winter",
        # "how to create a resume for a first job",
        # "list 5 famous inventors from the Industrial Revolution",
        # "describe the process of making mozzarella cheese",
        # "what is the role of the moon in eclipses",
        # "how does a car GPS navigate routes",
        # "what are the effects of sleep deprivation on children's development",
        # "suggest 3 ways to promote wind energy",
        # "explain the concept of acceleration due to gravity",
        # "what is the history of Alexander Graham Bell and the telephone",
        # "how to grow tomatoes in a greenhouse",
        # "list 5 types of reptiles and their defense mechanisms",
        # "describe the function of the eyes in color vision",
        # "what is the difference between a virus and bacteria in terms of treatment",
        # "how does a washing machine's agitator work",
        # "what are the benefits of a vegan diet for animals",
        # "suggest 5 puzzle games for adults",
        # "explain the concept of the water cycle and evaporation",
        # "what causes a landslide after heavy rain",
        # "how to write a haiku poem",
        # "list 5 major mountain peaks in South America",
        # "describe the process of making craft beer",
        # "what is the role of the immune system in allergies",
        # "how does a drone's battery power the device",
        # "what are the effects of noise pollution on marine life",
        # "suggest 3 ways to reduce food waste in schools",
        # "explain the concept of Newton's laws of motion",
        # "what is the history of Thomas Edison and the light bulb",
        # "how to build a campfire in wet conditions",
        # "list 5 types of insects and their life cycles",
        # "describe the function of the skeletal system in support",
        # "what is the difference between a lake and an estuary",
        # "how does a toaster's thermostat work",
        # "what are the benefits of reading aloud to children",
        # "suggest 5 board games for teenagers",
        # "explain the concept of chemical reactions in cooking",
        # "what causes a cyclone in the Pacific Ocean",
        # "how to create a budget for a small business",
        # "list 5 famous scientists and their contributions to physics",
        # "describe the process of making dark chocolate",
        # "what is the role of the Sun in climate change",
        # "how does a remote control toy car steer",
        # "what are the effects of deforestation on soil erosion",
        # "suggest 3 ways to improve public playgrounds",
        # "explain the concept of electromagnetic waves",
        # "what is the history of film photography",
        # "how to tie a knot for securing a load",
        # "list 5 types of rocks and their mineral composition",
        # "describe the function of the ears in balance",
        # "what is the difference between a static website and a dynamic website",
        # "how does a sprinkler system detect fire",
        # "what are the benefits of outdoor exercise",
        # "suggest 5 documentaries about technology",
        # "explain the concept of gravity on different planets",
        # "what causes a drought in agricultural areas",
        # "how to make homemade pizza with a crispy crust",
        # "list 5 programming frameworks for frontend development",
        # "describe the process of making beeswax candles",
        # "what is the role of the ozone layer in climate",
        # "how does a speaker's diaphragm work",
        # "what are the effects of air pollution on human lungs",
        # "suggest 3 ways to support local artisans",
        # "explain the concept of speed and velocity",
        # "what is the history of the first computer",
        # "how to grow herbs in a windowsill garden",
        # "list 5 types of mammals and their gestation periods",
        # "describe the function of the heart's chambers",
        # "what is the difference between a tornado and a cyclone",
        # "how does a dishwasher's spray arm work",
        # "what are the benefits of mindfulness for children",
        # "suggest 5 science fiction short stories",
        # "explain the concept of condensation and dew formation",
        # "what causes a hailstorm with large hailstones",
        # "how to write a movie review",
        # "list 5 major rivers in Europe",
        # "describe the process of making grape jam",
        # "what is the role of the atmosphere in protecting against meteoroids",
        # "how does a barcode scanner connect to a computer",
        # "what are the effects of global warming on wildlife migration",
        # "suggest 3 ways to reduce carbon emissions from homes",
        # "explain the concept of mass and inertia",
        # "what is the history of Twitter",
        # "how to plant a flower garden for pollinators",
        # "list 5 types of amphibians and their predators",
        # "describe the function of the lungs in respiration rate",
        # "what is the difference between a hurricane watch and warning",
        # "how does a blender's speed settings work",
        # "what are the benefits of meditation for focus",
        # "suggest 5 strategy board games for adults",
        # "explain the concept of photosynthesis in algae",
        # "what causes a dust storm in urban areas",
        # "how to make a protein smoothie",
        # "list 5 programming languages for machine learning",
        # "describe the process of making pottery glaze",
        # "what is the role of the liver in bile production",
        # "how does a smartwatch connect to a smartphone",
        # "what are the effects of air pollution on climate change",
        # "suggest 3 ways to improve water quality in aquariums",
        # "explain the concept of energy conservation",
        # "what is the history of hybrid cars",
        # "how to do a basic yoga breathing exercise",
        # "list 5 types of birds of prey and their hunting techniques",
        # "describe the function of the skin in sensation",
        # "what is the difference between a tablet and an e-reader",
        # "how does a vacuum sealer's seal bar work",
        # "what are the benefits of learning a second language for travel",
        # "suggest 5 movies about the International Space Station",
        # "explain the concept of magnetic poles",
        # "what causes a snowstorm with heavy snowfall",
        # "how to create a resume for a career change",
        # "list 5 famous inventors from the 20th century",
        # "describe the process of making cheddar cheese",
        # "what is the role of the moon in Earth's rotation",
        # "how does a GPS track location",
        # "what are the effects of sleep deprivation on decision making",
        # "suggest 3 ways to promote geothermal energy",
        # "explain the concept of centripetal acceleration",
        # "what is the history of the telephone switchboard",
        # "how to grow tomatoes in hanging baskets",
        # "list 5 types of reptiles and their reproductive methods",
        # "describe the function of the eyes in low light",
        # "what is the difference between a virus and a prion",
        # "how does a washing machine's spin cycle work",
        # "what are the benefits of a plant-based diet for heart health",
        # "suggest 5 puzzle games for kids",
        # "explain the concept of the water cycle and runoff",
        # "what causes a landslide on steep slopes",
        # "how to write a limerick poem",
        # "list 5 major mountain peaks in Africa",
        # "describe the process of making lager beer",
        # "what is the role of the immune system in vaccination",
        # "how does a drone's propeller create lift",
        # "what are the effects of noise pollution on human hearing",
        # "suggest 3 ways to reduce food waste in hospitals",
        # "explain the concept of force and motion in sports",
        # "what is the history of fluorescent light bulbs",
        # "how to build a campfire for cooking",
        # "list 5 types of insects and their economic importance",
        # "describe the function of the muscular system in movement",
        # "what is the difference between a lake and a lagoon",
        # "how does a toaster's pop-up mechanism work",
        # "what are the benefits of reading for critical thinking",
        # "suggest 5 board games for family game night",
        # "explain the concept of chemical reactions in rusting",
        # "what causes a cyclone in the Atlantic Ocean",
        # "how to create a personal savings plan",
        # "list 5 famous scientists and their contributions to chemistry",
        # "describe the process of making milk chocolate",
        # "what is the role of the Sun in weather patterns",
        # "how does a remote control helicopter fly",
        # "what are the effects of deforestation on indigenous communities",
        # "suggest 3 ways to improve public libraries",
        # "explain the concept of visible light spectrum",
        # "what is the history of digital cameras",
        # "how to tie a knot for fishing",
        # "list 5 types of rocks and their formation processes",
        # "describe the function of the ears in hearing loss",
        # "what is the difference between a website and a portal",
        # "how does a sprinkler system's timer work",
        # "what are the benefits of spending time in nature for creativity",
        # "suggest 5 documentaries about space exploration",
        # "explain the concept of gravity and black holes",
        # "what causes a drought in rainforest areas",
        # "how to make homemade pizza without yeast",
        # "list 5 programming frameworks for mobile games",
        # "describe the process of making soy candles",
        # "what is the role of the ozone layer in the atmosphere",
        # "how does a speaker's crossover network work",
        # "what are the effects of air pollution on historical monuments",
        # "suggest 3 ways to support local musicians",
        # "explain the concept of average speed and instantaneous speed",
        # "what is the history of the abacus and early computing",
        # "how to grow herbs in hydroponics",
        # "list 5 types of mammals and their social behaviors",
        # "describe the function of the heart's valves",
        # "what is the difference between a tornado and a funnel cloud",
        # "how does a dishwasher's detergent dispenser work",
        # "what are the benefits of mindfulness for stress reduction",
        # "suggest 5 science fiction films from the 21st century",
        # "explain the concept of precipitation in the water cycle",
        # "what causes a hailstorm in spring",
        # "how to write a concert review",
        # "list 5 major rivers in Antarctica",
        # "describe the process of making raspberry jam",
        # "what is the role of the atmosphere in sound transmission",
        # "how does a barcode scanner's laser work",
        # "what are the effects of global warming on coral reefs",
        # "suggest 3 ways to reduce carbon emissions from industry",
        # "explain the concept of mass and gravity",
        # "what is the history of Instagram",
        # "how to plant a butterfly garden",
        # "list 5 types of amphibians and their conservation efforts",
        # "describe the function of the lungs in exercise",
        # "what is the difference between a hurricane and a superstorm",
        # "how does a blender's blade design affect blending",
        # "what are the benefits of meditation for sleep",
        # "suggest 5 strategy games for beginners",
        # "explain the concept of photosynthesis in bacteria",
        # "what causes a dust storm in farmland areas",
        # "how to make a fruit and vegetable smoothie",
        # "list 5 programming languages for scientific computing",
        # "describe the process of making pottery without a wheel",
        # "what is the role of the liver in protein metabolism",
        # "how does a smartwatch measure steps",
        # "what are the effects of air pollution on plant growth",
        # "suggest 3 ways to improve water quality in swimming pools",
        # "explain the concept of energy transfer",
        # "what is the history of the first electric car",
        # "how to do a basic yoga relaxation pose",
        # "list 5 types of birds of prey and their conservation status",
        # "describe the function of the skin in vitamin D production",
        # "what is the difference between a tablet and a phablet",
        # "how does a vacuum sealer's vacuum pump work",
        # "what are the benefits of learning a second language for cognitive function",
        # "suggest 5 movies about black holes",
        # "explain the concept of magnetic materials",
        # "what causes a snowstorm with high winds",
        # "how to create a resume with no work experience",
        # "list 5 famous inventors from ancient times",
        # "describe the process of making goat cheese",
        # "what is the role of the moon in lunar phases",
        # "how does a GPS determine elevation",
        # "what are the effects of sleep deprivation on mood",
        # "suggest 3 ways to promote biomass energy",
        # "explain the concept of angular acceleration",
        # "what is the history of the telephone booth",
        # "how to grow tomatoes in a small space",
        # "list 5 types of reptiles and their habitat loss issues",
        # "describe the function of the eyes in focusing",
        # "what is the difference between a virus and a viroid",
        # "how does a washing machine's water level sensor work",
        # "what are the benefits of a plant-based diet for weight management",
        # "suggest 5 puzzle games for seniors",
        # "explain the concept of the water cycle and infiltration",
        # "what causes a landslide during an earthquake",
        # "how to write a sonnet poem",
        # "list 5 major mountain peaks in Antarctica",
        # "describe the process of making stout beer",
        # "what is the role of the immune system in autoimmune diseases",
        # "how does a drone's flight controller work",
        # "what are the effects of noise pollution on sleep",
        # "suggest 3 ways to reduce food waste in hotels",
        # "explain the concept of force in physics",
        # "what is the history of LED light bulbs",
        # "how to build a campfire for warmth",
        # "list 5 types of insects and their symbiotic relationships",
        # "describe the function of the muscular system in posture",
        # "what is the difference between a lake and a fjord",
        # "how does a toaster's crumb tray work",
        # "what are the benefits of reading for empathy",
        # "suggest 5 board games for rainy days",
        # "explain the concept of chemical reactions in digestion",
        # "what causes a cyclone in the Southern Hemisphere",
        # "how to create a budget for a vacation",
        # "list 5 famous scientists and their contributions to astronomy",
        # "describe the process of making white chocolate",
        # "what is the role of the Sun in the water cycle",
        # "how does a remote control boat move through water",
        # "what are the effects of deforestation on local climate",
        # "suggest 3 ways to improve public transportation accessibility",
        # "explain the concept of ultraviolet light",
        # "what is the history of camera phones",
        # "how to tie a knot for securing a boat",
        # "list 5 types of rocks and their uses in construction",
        # "describe the function of the ears in sound localization",
        # "what is the difference between a website and a web portal",
        # "how does a sprinkler system's pressure regulator work",
        # "what are the benefits of spending time in nature for physical health",
        # "suggest 5 documentaries about the universe",
        # "explain the concept of gravity on Earth and the moon",
        # "what causes a drought in coastal areas",
        # "how to make homemade pizza with whole wheat crust",
        # "list 5 programming frameworks for desktop applications",
        # "describe the process of making scented soy candles",
        # "what is the role of the ozone layer in climate regulation",
        # "how does a speaker's enclosure affect sound quality",
        # "what are the effects of air pollution on crop yields",
        # "suggest 3 ways to support local theaters",
        # "explain the concept of speed in everyday life",
        # "what is the history of the first mechanical computer",
        # "how to grow herbs in a vertical garden",
        # "list 5 types of mammals and their communication methods",
        # "describe the function of the heart in exercise",
        # "what is the difference between a tornado and a microburst",
        # "how does a dishwasher's drying cycle work",
        # "what are the benefits of mindfulness for children's behavior",
        # "suggest 5 science fiction novels for young adults",
        # "explain the concept of transpiration in the water cycle",
        # "what causes a hailstorm in thunderstorms",
        # "how to write a music review",
        # "list 5 major rivers in Asia",
        # "describe the process of making blueberry jam",
        # "what is the role of the atmosphere in cloud formation",
        # "how does a barcode scanner's decoder work",
        # "what are the effects of global warming on penguins",
        # "suggest 3 ways to reduce carbon emissions from air travel",
        # "explain the concept of mass in chemistry",
        # "what is the history of Snapchat",
        # "how to plant a shade garden",
        # "list 5 types of amphibians and their unique adaptations",
        # "describe the function of the lungs in diving",
        # "what is the difference between a hurricane and a tropical storm",
        # "how does a blender's wattage affect performance",
        # "what are the benefits of meditation for pain management",
        # "suggest 5 strategy games for large groups",
        # "explain the concept of photosynthesis in cacti",
        # "what causes a dust storm in arid regions",
        # "how to make a green smoothie with spinach",
        # "list 5 programming languages for backend APIs",
        # "describe the process of making ceramic pottery",
        # "what is the role of the liver in carbohydrate metabolism",
        # "how does a smartwatch measure distance",
        # "what are the effects of air pollution on asthma",
        # "suggest 3 ways to improve water quality in rivers and streams",
        # "explain the concept of energy in food",
        # "what is the history of electric vehicles before Tesla",
        # "how to do a basic yoga stretch for flexibility",
        # "list 5 types of birds of prey and their wing shapes",
        # "describe the function of the skin in wound healing",
        # "what is the difference between a tablet and a laptop",
        # "how does a vacuum sealer's heat seal work",
        # "what are the benefits of learning a second language for career",
        # "suggest 5 movies about the moon landing",
        # "explain the concept of magnetic fields around Earth",
        # "what causes a snowstorm in mountainous areas",
        # "how to create a resume for a technical job",
        # "list 5 famous inventors and their failed inventions",
        # "describe the process of making cream cheese",
        # "what is the role of the moon in Earth's axial tilt",
        # "how does a GPS receiver work",
        # "what are the effects of sleep deprivation on immune function",
        # "suggest 3 ways to promote tidal energy",
        # "explain the concept of linear acceleration",
        # "what is the history of the first mobile phone",
        # "how to grow tomatoes upside down",
        # "list 5 types of reptiles and their lifespan",
        # "describe the function of the eyes in depth perception",
        # "what is the difference between a virus and a bacteriophage",
        # "how does a washing machine's door lock work",
        # "what are the benefits of a plant-based diet for diabetes",
        # "suggest 5 puzzle games for road trips",
        # "explain the concept of the water cycle and sublimation",
        # "what causes a landslide in volcanic areas",
        # "how to write a free verse poem",
        # "list 5 major mountain peaks in North America",
        # "describe the process of making wheat beer",
        # "what is the role of the immune system in cancer",
        # "how does a drone's battery life vary with use",
        # "what are the effects of noise pollution on cardiovascular health",
        # "suggest 3 ways to reduce food waste in grocery stores",
        # "explain the concept of force in everyday life",
        # "what is the history of compact fluorescent light bulbs",
        # "how to build a campfire in windy conditions",
        # "list 5 types of insects and their economic impact",
        # "describe the function of the muscular system in reflexes",
        # "what is the difference between a lake and a marsh",
        # "how does a toaster's heating element heat up",
        # "what are the benefits of reading for vocabulary",
        # "suggest 5 board games for educational purposes",
        # "explain the concept of chemical reactions in combustion",
        # "what causes a cyclone in the Indian Ocean",
        # "how to create a budget for college students",
        # "list 5 famous scientists and their contributions to biology",
        # "describe the process of making dark chocolate truffles",
        # "what is the role of the Sun in photosynthesis",
        # "how does a remote control plane stay airborne",
        # "what are the effects of deforestation on water cycles",
        # "suggest 3 ways to improve public transportation safety",
        # "explain the concept of infrared light",
        # "what is the history of digital single-lens reflex cameras",
        # "how to tie a knot for climbing",
        # "list 5 types of rocks and their hardness",
        # "describe the function of the ears in hearing aids",
        # "what is the difference between a website and a web service",
        # "how does a sprinkler system's anti-siphon valve work",
        # "what are the benefits of spending time in nature for attention",
        # "suggest 5 documentaries about black holes",
        # "explain the concept of gravity and orbits",
        # "what causes a drought in grassland areas",
        # "how to make homemade pizza with gluten-free crust",
        # "list 5 programming frameworks for game engines",
        # "describe the process of making beeswax candles with essential oils",
        # "what is the role of the ozone layer in UV radiation absorption",
        # "how does a speaker's cone material affect sound",
        # "what are the effects of air pollution on wildlife health",
        # "suggest 3 ways to support local bookstores",
        # "explain the concept of speed and distance",
        # "what is the history of the analytical engine",
        # "how to grow herbs in a hanging garden",
        # "list 5 types of mammals and their migration patterns",
        # "describe the function of the heart in heart disease",
        # "what is the difference between a tornado and a gustnado",
        # "how does a dishwasher's filter work",
        # "what are the benefits of mindfulness for productivity",
        # "suggest 5 science fiction films from the 20th century",
        # "explain the concept of condensation in the water cycle",
        # "what causes a hailstorm in winter",
        # "how to write a theater review",
        # "list 5 major rivers in South America",
        # "describe the process of making peach jam",
        # "what is the role of the atmosphere in wind formation",
        # "how does a barcode scanner's software work",
        # "what are the effects of global warming on polar bears",
        # "suggest 3 ways to reduce carbon emissions from shipping",
        # "explain the concept of mass in physics",
        # "what is the history of TikTok",
        # "how to plant a rock garden",
        # "list 5 types of amphibians and their feeding habits",
        # "describe the function of the lungs in respiratory diseases",
        # "what is the difference between a hurricane and a cyclone",
        # "how does a blender's container material affect use",
        # "what are the benefits of meditation for blood pressure",
        # "suggest 5 strategy games for advanced players",
        # "explain the concept of photosynthesis in underwater plants",
        # "what causes a dust storm in semi-arid regions",
        # "how to make a smoothie with protein powder",
        # "list 5 programming languages for data analysis",
        # "describe the process of making raku pottery",
        # "what is the role of the liver in fat metabolism",
        # "how does a smartwatch monitor sleep patterns",
        # "what are the effects of air pollution on cardiovascular health",
        # "suggest 3 ways to improve water quality in reservoirs",
        # "explain the concept of energy in physics",
        # "what is the history of hybrid vehicles",
        # "how to do a basic yoga balance pose",
        # "list 5 types of birds of prey and their size",
        # "describe the function of the skin in aging",
        # "what is the difference between a tablet and a portable media player",
        # "how does a vacuum sealer's control panel work",
        # "what are the benefits of learning a second language for cultural understanding",
        # "suggest 5 movies about space colonization",
        # "explain the concept of magnetic poles and their interactions",
        # "what causes a snowstorm in flat areas",
        # "how to create a resume for a creative job",
        # "list 5 famous inventors and their inspiration",
        # "describe the process of making mascarpone cheese",
        # "what is the role of the moon in Earth's climate",
        # "how does a GPS determine speed",
        # "what are the effects of sleep deprivation on cognitive function",
        # "suggest 3 ways to promote wave energy",
        # "explain the concept of acceleration in sports",
        # "what is the history of the payphone",
        # "how to grow tomatoes in a container garden",
        # "list 5 types of reptiles and their size range",
        # "describe the function of the eyes in aging",
        # "what is the difference between a virus and a plasmid",
        # "how does a washing machine's motor work",
        # "what are the benefits of a plant-based diet for kidney health",
        # "suggest 5 puzzle games for family road trips",
        # "explain the concept of the water cycle and evaporation from oceans",
        # "what causes a landslide in clay-rich soils",
        # "how to write a concrete poem",
        # "list 5 major mountain peaks in Europe",
        # "describe the process of making porter beer",
        # "what is the role of the immune system in transplantation",
        # "how does a drone's camera stabilize footage",
        # "what are the effects of noise pollution on children's learning",
        # "suggest 3 ways to reduce food waste in military facilities",
        # "explain the concept of force and pressure in fluids",
        # "what is the history of halogen light bulbs",
        # "how to build a campfire for signaling",
        # "list 5 types of insects and their predators",
        # "describe the function of the muscular system in exercise",
        # "what is the difference between a lake and a swamp",
        # "how does a toaster's browning control work",
        # "what are the benefits of reading for memory",
        # "suggest 5 board games for holiday gatherings",
        # "explain the concept of chemical reactions in batteries",
        # "what causes a cyclone in the Southern Hemisphere",
        # "how to create a budget for a family",
        # "list 5 famous scientists and their contributions to geology",
        # "describe the process of making chocolate bars",
        # "what is the role of the Sun in seasons",
        # "how does a remote control submarine work underwater",
        # "what are the effects of deforestation on indigenous lands",
        # "suggest 3 ways to improve public transportation frequency",
        # "explain the concept of visible light and color",
        # "what is the history of instant cameras",
        # "how to tie a knot for securing a tent",
        # "list 5 types of rocks and their color variations",
        # "describe the function of the ears in tinnitus",
        # "what is the difference between a website and a web application",
        # "how does a sprinkler system's backflow preventer work",
        # "what are the benefits of spending time in nature for stress relief",
        # "suggest 5 documentaries about the solar system",
        # "explain the concept of gravity and weightlessness",
        # "what causes a drought in mountainous areas",
        # "how to make homemade pizza with cauliflower crust",
        # "list 5 programming frameworks for cross-platform development",
        # "describe the process of making scented candles with dried flowers",
        # "what is the role of the ozone layer in atmospheric chemistry",
        # "how does a speaker's voice coil work",
        # "what are the effects of air pollution on fetal development",
        # "suggest 3 ways to support local farmers markets",
        # "explain the concept of speed in physics",
        # "what is the history of the first laptop computer",
        # "how to grow herbs in a window garden",
        # "list 5 types of mammals and their diet",
        # "describe the function of the heart in fetal development",
        # "what is the difference between a tornado and a fire whirl",
        # "how does a dishwasher's circulation pump work",
        # "what are the benefits of mindfulness for depression",
        # "suggest 5 science fiction novels for adults",
        # "explain the concept of precipitation types in the water cycle",
        # "what causes a hailstorm in autumn",
        # "how to write a poetry analysis",
        # "list 5 major rivers in Africa",
        # "describe the process of making strawberry-rhubarb jam",
        # "what is the role of the atmosphere in precipitation",
        # "how does a barcode scanner's interface work with POS systems",
        # "what are the effects of global warming on sea turtles",
        # "suggest 3 ways to reduce carbon emissions from rail transport",
        # "explain the concept of mass and volume",
        # "what is the history of Pinterest",
        # "how to plant a wildflower garden",
        # "list 5 types of amphibians and their coloration",
        # "describe the function of the lungs in high altitudes",
        # "what is the difference between a hurricane and a typhoon",
        # "how does a blender's lid design prevent spills",
        # "what are the benefits of meditation for addiction recovery",
        # "suggest 5 strategy games for kids",
        # "explain the concept of photosynthesis in desert plants",
        # "what causes a dust storm in agricultural regions",
        # "how to make a smoothie with frozen fruit",
        # "list 5 programming languages for embedded systems",
        # "describe the process of making porcelain pottery",
        # "what is the role of the liver in drug metabolism",
        # "how does a smartwatch receive notifications",
        # "what are the effects of air pollution on respiratory diseases",
        # "suggest 3 ways to improve water quality in groundwater",
        # "explain the concept of energy in chemistry",
        # "what is the history of electric scooters",
        # "how to do a basic yoga twist pose",
        # "list 5 types of birds of prey and their feather adaptations",
        # "describe the function of the skin in sun protection",
        # "what is the difference between a tablet and a convertible laptop",
        # "how does a vacuum sealer's accessory port work",
        # "what are the benefits of learning a second language for brain health",
        # "suggest 5 movies about interstellar travel",
        # "explain the concept of magnetic field lines",
        # "what causes a snowstorm with ice pellets",
        # "how to create a resume for an internship",
        # "list 5 famous inventors and their awards",
        # "describe the process of making cottage cheese",
        # "what is the role of the moon in eclipses",
        # "how does a GPS work in remote areas",
        # "what are the effects of sleep deprivation on driving",
        # "suggest 3 ways to promote geothermal energy in homes",
        # "explain the concept of centripetal acceleration in circular motion",
        # "what is the history of the rotary dial telephone",
        # "how to grow tomatoes in a greenhouse",
        # "list 5 types of reptiles and their habitat preferences",
        # "describe the function of the eyes in eye diseases",
        # "what is the difference between a virus and a viroid",
        # "how does a washing machine's suspension system work",
        # "what are the benefits of a plant-based diet for digestion",
        # "suggest 5 puzzle games for rainy afternoons",
        # "explain the concept of the water cycle and cloud formation",
        # "what causes a landslide in soil with high water content",
        # "how to write a limerick poem",
        # "list 5 major mountain peaks in Australia",
        # "describe the process of making brown ale beer",
        # "what is the role of the immune system in pregnancy",
        # "how does a drone's obstacle avoidance system work",
        # "what are the effects of noise pollution on wildlife reproduction",
        # "suggest 3 ways to reduce food waste in military rations",
        # "explain the concept of force and motion in machines",
        # "what is the history of xenon light bulbs",
        # "how to build a campfire for warmth in cold weather",
        # "list 5 types of insects and their metamorphosis stages",
        # "describe the function of the muscular system in strength",
        # "what is the difference between a lake and a bog",
        # "how does a toaster's heating element turn off",
        # "what are the benefits of reading for writing skills",
        # "suggest 5 board games for summer vacations",
        # "explain the concept of chemical reactions in photosynthesis",
        # "what causes a cyclone in the Pacific Ocean",
        # "how to create a budget for a small business startup",
        # "list 5 famous scientists and their contributions to meteorology",
        # "describe the process of making white chocolate bark",
        # "what is the role of the Sun in climate",
        # "how does a remote control robot move",
        # "what are the effects of deforestation on soil quality",
        # "suggest 3 ways to improve public transportation comfort",
        # "explain the concept of ultraviolet radiation and its effects",
        # "what is the history of camera lenses",
        # "how to tie a knot for securing a load on a roof rack",
        # "list 5 types of rocks and their texture",
        # "describe the function of the ears in newborns",
        # "what is the difference between a website and a blog platform",
        # "how does a sprinkler system's valve manifold work",
        # "what are the benefits of spending time in nature for depression",
        # "suggest 5 documentaries about Mars",
        # "explain the concept of gravity and planetary motion",
        # "what causes a drought in urban areas",
        # "how to make homemade pizza with whole grain crust",
        # "list 5 programming frameworks for API development",
        # "describe the process of making beeswax candles with wicks",
        # "what is the role of the ozone layer in the stratosphere",
        # "how does a speaker's spider suspension work",
        # "what are the effects of air pollution on neurological development",
        # "suggest 3 ways to support local craft breweries",
        # "explain the concept of average speed in physics",
        # "what is the history of the first personal computer",
        # "how to grow herbs in a container garden",
        # "list 5 types of mammals and their defense mechanisms",
        # "describe the function of the heart in athletes",
        # "what is the difference between a tornado and a waterspout",
        # "how does a dishwasher's water inlet valve work",
        # "what are the benefits of mindfulness for anxiety disorders",
        # "suggest 5 science fiction films for kids",
        # "explain the concept of evaporation in the water cycle",
        # "what causes a hailstorm in spring thunderstorms",
        # "how to write a book analysis",
        # "list 5 major rivers in North America",
        # "describe the process of making apple jam",
        # "what is the role of the atmosphere in protecting life",
        # "how does a barcode scanner's output work with inventory systems",
        # "what are the effects of global warming on coral bleaching",
        # "suggest 3 ways to reduce carbon emissions from construction",
        # "explain the concept of mass and density",
        # "what is the history of LinkedIn",
        # "how to plant a container garden for small spaces",
        # "list 5 types of amphibians and their mating behaviors",
        # "describe the function of the lungs in smokers",
        # "what is the difference between a hurricane and a tropical depression",
        # "how does a blender's motor cooling system work",
        # "what are the benefits of meditation for chronic pain",
        # "suggest 5 strategy games for classroom use",
        # "explain the concept of photosynthesis in rainforest plants",
        # "what causes a dust storm in dry lake beds",
        # "how to make a smoothie with green vegetables",
        # "list 5 programming languages for game scripting",
        # "describe the process of making earthenware pottery",
        # "what is the role of the liver in glycogen storage",
        # "how does a smartwatch track heart rate variability",
        # "what are the effects of air pollution on skin health",
        # "suggest 3 ways to improve water quality in fish tanks",
        # "explain the concept of energy transfer in food chains",
        # "what is the history of electric bikes",
        # "how to do a basic yoga forward fold",
        # "list 5 types of birds of prey and their hunting times",
        # "describe the function of the skin in hydration",
        # "what is the difference between a tablet and a handheld gaming device",
        # "how does a vacuum sealer's seal time control work",
        # "what are the benefits of learning a second language for travel",
        # "suggest 5 movies about the Hubble Space Telescope",
        # "explain the concept of magnetic domains in materials",
        # "what causes a snowstorm with freezing rain",
        # "how to create a resume for a management position",
        # "list 5 famous inventors and their biographies",
        # "describe the process of making ricotta cheese",
        # "what is the role of the moon in Earth's tides",
        # "how does a GPS work indoors",
        # "what are the effects of sleep deprivation on learning",
        # "suggest 3 ways to promote solar energy in communities",
        # "explain the concept of angular acceleration in rotating objects",
        # "what is the history of the cordless telephone",
        # "how to grow tomatoes in a hydroponic system",
        # "list 5 types of reptiles and their activity patterns",
        # "describe the function of the eyes in animals",
        # "what is the difference between a virus and a retrovirus",
        # "how does a washing machine's drain pump work",
        # "what are the benefits of a plant-based diet for skin health",
        # "suggest 5 puzzle games for educational settings",
        # "explain the concept of the water cycle and groundwater",
        # "what causes a landslide in volcanic ash deposits",
        # "how to write a cinquain poem",
        # "list 5 major mountain peaks in Asia",
        # "describe the process of making India pale ale beer",
        # "what is the role of the immune system in aging",
        # "how does a drone's battery charging system work",
        # "what are the effects of noise pollution on bird songs",
        # "suggest 3 ways to reduce food waste in catering services",
        # "explain the concept of force and motion in sports equipment",
        # "what is the history of LED light bulbs development",
        # "how to build a campfire for cooking in the wilderness",
        # "list 5 types of insects and their beneficial roles in gardens",
        # "describe the function of the muscular system in endurance",
        # "what is the difference between a lake and a slough",
        # "how does a toaster's power cord work",
        # "what are the benefits of reading for language development",
        # "suggest 5 board games for birthday parties",
        # "explain the concept of chemical reactions in digestion",
        # "what causes a cyclone in the Atlantic Ocean",
        # "how to create a budget for retirement",
        # "list 5 famous scientists and their contributions to ecology",
        # "describe the process of making chocolate fudge",
        # "what is the role of the Sun in photosynthesis",
        # "how does a remote control car's battery work",
        # "what are the effects of deforestation on rainfall patterns",
        # "suggest 3 ways to improve public transportation technology",
        # "explain the concept of infrared radiation and heat",
        # "what is the history of camera sensors",
        # "how to tie a knot for securing a kayak",
        # "list 5 types of rocks and their fossil content",
        # "describe the function of the ears in different species",
        # "what is the difference between a website and a content management system",
        # "how does a sprinkler system's flow control valve work",
        # "what are the benefits of spending time in nature for attention deficit disorder",
        # "suggest 5 documentaries about the International Space Station",
        # "explain the concept of gravity and its discovery by Newton",
        # "what causes a drought in Mediterranean climates",
        # "how to make homemade pizza with a whole grain crust",
        # "list 5 programming frameworks for game development",
        # "describe the process of making soy candles with fragrance oils",
        # "what is the role of the ozone layer in protecting marine life",
        # "how does a speaker's surround material affect sound",
        # "what are the effects of air pollution on birth outcomes",
        # "suggest 3 ways to support local wineries",
        # "explain the concept of speed in everyday activities",
        # "what is the history of the first electronic computer",
        # "how to grow herbs in a hanging basket garden",
        # "list 5 types of mammals and their intelligence",
        # "describe the function of the heart in heart failure",
        # "what is the difference between a tornado and a dust devil",
        # "how does a dishwasher's heating element work",
        # "what are the benefits of mindfulness for children with ADHD",
        # "suggest 5 science fiction novels for middle schoolers",
        # "explain the concept of condensation in the water cycle",
        # "what causes a hailstorm in summer thunderstorms",
        # "how to write a short story analysis",
        # "list 5 major rivers in Europe",
        # "describe the process of making blackberry jam",
        # "what is the role of the atmosphere in sound",
        # "how does a barcode scanner's wireless connection work",
        # "what are the effects of global warming on Arctic ice",
        # "suggest 3 ways to reduce carbon emissions from manufacturing",
        # "explain the concept of mass in astronomy",
        # "what is the history of Reddit",
        # "how to plant a succulent garden",
        # "list 5 types of amphibians and their conservation status",
        # "describe the function of the lungs in singers",
        # "what is the difference between a hurricane and a super typhoon",
        # "how does a blender's motor power affect performance",
        # "what are the benefits of meditation for post-traumatic stress disorder",
        # "suggest 5 strategy games for family game night",
        # "explain the concept of photosynthesis in algae",
        # "what causes a dust storm in desert regions",
        # "how to make a smoothie with protein and greens",
        # "list 5 programming languages for web scraping",
        # "describe the process of making stoneware pottery",
        # "what is the role of the liver in bile production",
        # "how does a smartwatch measure blood oxygen levels",
        # "what are the effects of air pollution on cognitive function",
        # "suggest 3 ways to improve water quality in swimming pools",
        # "explain the concept of energy conservation in physics",
        # "what is the history of electric skateboards",
        # "how to do a basic yoga cat-cow pose",
        # "list 5 types of birds of prey and their geographic range",
        # "describe the function of the skin in immunity",
        # "what is the difference between a tablet and a smart display",
        # "how does a vacuum sealer's vacuum level control work",
        # "what are the benefits of learning a second language for cultural awareness",
        # "suggest 5 movies about space shuttles",
        # "explain the concept of magnetic field strength",
        # "what causes a snowstorm with blizzard conditions",
        # "how to create a resume for a teaching position",
        # "list 5 famous inventors and their patents",
        # "describe the process of making feta cheese",
        # "what is the role of the moon in Earth's rotation",
        # "how does a GPS determine direction",
        # "what are the effects of sleep deprivation on creativity",
        # "suggest 3 ways to promote wind energy in communities",
        # "explain the concept of linear acceleration in vehicles",
        # "what is the history of the mobile phone charger",
        # "how to grow tomatoes in a raised bed garden",
        # "list 5 types of reptiles and their temperature regulation",
        # "describe the function of the eyes in different animals",
        # "what is the difference between a virus and a bacterium",
        # "how does a washing machine's control panel work",
        # "what are the benefits of a plant-based diet for arthritis",
        # "suggest 5 puzzle games for family gatherings",
        # "explain the concept of the water cycle and surface runoff",
        # "what causes a landslide in mountainous regions",
        # "how to write a haiku poem",
        # "list 5 major mountain peaks in Africa",
        # "describe the process of making stout beer",
        # "what is the role of the immune system in fighting infections",
        # "how does a drone's remote controller work",
        # "what are the effects of noise pollution on aquatic life",
        # "suggest 3 ways to reduce food waste in school cafeterias",
        # "explain the concept of force and pressure in everyday life",
        # "what is the history of compact fluorescent lamps (CFLs)",
        # "how to build a campfire for cooking over",
        # "list 5 types of insects and their communication methods",
        # "describe the function of the muscular system in balance",
        # "what is the difference between a lake and a reservoir",
        # "how does a toaster's heating element material affect performance",
        # "what are the benefits of reading for academic success",
        # "suggest 5 board games for classroom learning",
        # "explain the concept of chemical reactions in rusting",
        # "what causes a cyclone in the Indian Ocean",
        # "how to create a budget for a student",
        # "list 5 famous scientists and their contributions to genetics",
        # "describe the process of making chocolate mousse",
        # "what is the role of the Sun in the solar system",
        # "how does a remote control helicopter's rotor work",
        # "what are the effects of deforestation on carbon sequestration",
        # "suggest 3 ways to improve public transportation accessibility for disabled",
        # "explain the concept of visible light and its spectrum",
        # "what is the history of digital camera sensors",
        # "how to tie a knot for securing a surfboard",
        # "list 5 types of rocks and their origin",
        # "describe the function of the ears in hearing loss prevention",
        # "what is the difference between a website and a web portal",
        # "how does a sprinkler system's timer programming work",
        # "what are the benefits of spending time in nature for creativity",
        # "suggest 5 documentaries about the moon",
        # "explain the concept of gravity and its effect on weight",
        # "what causes a drought in tropical regions",
        # "how to make homemade pizza with a cauliflower crust",
        # "list 5 programming frameworks for mobile app development",
        # "describe the process of making beeswax candles with honey",
        # "what is the role of the ozone layer in the environment",
        # "how does a speaker's magnet affect sound production",
        # "what are the effects of air pollution on plant reproduction",
        # "suggest 3 ways to support local coffee shops",
        # "explain the concept of speed and velocity in physics",
        # "what is the history of the first computer mouse",
        # "how to grow herbs in a vertical herb garden",
        # "list 5 types of mammals and their social structures",
        # "describe the function of the heart in different animals",
        # "what is the difference between a tornado and a funnel cloud",
        # "how does a dishwasher's detergent dispenser work",
        # "what are the benefits of mindfulness for stress in the workplace",
        # "suggest 5 science fiction films for teenagers",
        # "explain the concept of precipitation in the water cycle",
        # "what causes a hailstorm in winter storms",
        # "how to write a play analysis",
        # "list 5 major rivers in South America",
        # "describe the process of making raspberry jam",
        # "what is the role of the atmosphere in climate regulation",
        # "how does a barcode scanner's software decode barcodes",
        # "what are the effects of global warming on sea levels",
        # "suggest 3 ways to reduce carbon emissions from commercial buildings",
        # "explain the concept of mass in chemistry",
        # "what is the history of YouTube",
        # "how to plant a flower garden for cutting",
        # "list 5 types of amphibians and their habitat destruction",
        # "describe the function of the lungs in different species",
        # "what is the difference between a hurricane and a cyclone",
        # "how does a blender's blade speed affect blending",
        # "what are the benefits of meditation for sleep disorders",
        # "suggest 5 strategy games for adult game nights",
        # "explain the concept of photosynthesis in plants",
        # "what causes a dust storm in arid regions",
        # "how to make a smoothie with berries and yogurt",
        # "list 5 programming languages for data visualization",
        # "describe the process of making ceramic tiles",
        # "what is the role of the liver in detoxification",
        # "how does a smartwatch measure stress levels",
        # "what are the effects of air pollution on lung function",
        # "suggest 3 ways to improve water quality in drinking water",
        # "explain the concept of energy transformation in machines",
        # "what is the history of electric motorcycles",
        # "how to do a basic yoga downward dog pose",
        # "list 5 types of birds of prey and their nesting habits",
        # "describe the function of the skin in temperature regulation",
        # "what is the difference between a tablet and a laptop",
        # "how does a vacuum sealer's seal bar temperature work",
        # "what are the benefits of learning a second language for career advancement",
        # "suggest 5 movies about space exploration",
        # "explain the concept of magnetic poles and magnetic fields",
        # "what causes a snowstorm in coastal areas",
        # "how to create a resume for a healthcare position",
        # "list 5 famous inventors and their impact on society",
        # "describe the process of making goat cheese",
        # "what is the role of the moon in lunar eclipses",
        # "how does a GPS work in the mountains",
        # "what are the effects of sleep deprivation on immune function",
        # "suggest 3 ways to promote solar energy in schools",
        # "explain the concept of angular acceleration in sports",
        # "what is the history of the telephone answering machine",
        # "how to grow tomatoes in containers on a balcony",
        # "list 5 types of reptiles and their feeding habits",
        # "describe the function of the eyes in low light conditions",
        # "what is the difference between a virus and a prion",
        # "how does a washing machine's water heater work",
        # "what are the benefits of a plant-based diet for weight loss",
        # "suggest 5 puzzle games for long car rides",
        # "explain the concept of the water cycle and evaporation",
        # "what causes a landslide in earthquake-prone areas",
        # "how to write a sonnet poem",
        # "list 5 major mountain peaks in Europe",
        # "describe the process of making wheat beer",
        # "what is the role of the immune system in allergies",
        # "how does a drone's camera take photos",
        # "what are the effects of noise pollution on human health",
        # "suggest 3 ways to reduce food waste in hospitals",
        # "explain the concept of force and motion in physics",
        # "what is the history of incandescent light bulbs",
        # "how to build a campfire for warmth in winter",
        # "list 5 types of insects and their role in decomposition",
        # "describe the function of the muscular system in movement",
        # "what is the difference between a lake and a lagoon",
        # "how does a toaster's browning control mechanism work",
        # "what are the benefits of reading for vocabulary building",
        # "suggest 5 board games for family reunions",
        # "explain the concept of chemical reactions in combustion",
        # "what causes a cyclone in the Pacific Ocean",
        # "how to create a budget for a small business",
        # "list 5 famous scientists and their contributions to chemistry",
        # "describe the process of making chocolate truffles",
        # "what is the role of the Sun in weather",
        # "how does a remote control boat's motor work",
        # "what are the effects of deforestation on wildlife",
        # "suggest 3 ways to improve public transportation frequency",
        # "explain the concept of ultraviolet light and its effects",
        # "what is the history of camera film",
        # "how to tie a knot for securing a tent in windy conditions",
        # "list 5 types of rocks and their economic importance",
        # "describe the function of the ears in balance and equilibrium",
        # "what is the difference between a website and a web application",
        # "how does a sprinkler system's pressure gauge work",
        # "what are the benefits of spending time in nature for physical fitness",
        # "suggest 5 documentaries about the solar system",
        # "explain the concept of gravity and its role in the universe",
        # "what causes a drought in grassland regions",
        # "how to make homemade pizza with a gluten-free crust",
        # "list 5 programming frameworks for backend development",
        # "describe the process of making scented candles with essential oils",
        # "what is the role of the ozone layer in UV protection",
        # "how does a speaker's voice coil produce sound",
        # "what are the effects of air pollution on cardiovascular disease",
        # "suggest 3 ways to support local artists",
        # "explain the concept of speed in physics",
        # "what is the history of the first laptop computer",
        # "how to grow herbs in a windowsill garden",
        # "list 5 types of mammals and their migration patterns",
        # "describe the function of the heart in the circulatory system",
        # "what is the difference between a tornado and a microburst",
        # "how does a dishwasher's circulation pump work",
        # "what are the benefits of mindfulness for focus and concentration",
        # "suggest 5 science fiction novels for young adults"
    ]
    prompts = prompts[0:512]
    prompts = [
        tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )
        for prompt in prompts
    ]
    outputs = llm.generate(prompts[0:4], sampling_params)
    outputs = llm.generate(prompts[4:8], sampling_params)

    # for prompt, output in zip(prompts, outputs):
    #     print("\n")
    #     print(f"Prompt: {prompt!r}")
    #     print(f"Completion: {output['text']!r}")


if __name__ == "__main__":
    main()
