[build-system]
requires = ["setuptools>=61", "cmake>=3.18", "pybind11>=2.12.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanodeploy"
version = "0.2.0"
authors = [{ name = "Jinming Ma" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
description = "a lightweight LMDeploy implementation built from scratch"
requires-python = ">=3.10,<3.13"
dependencies = [
    "torch>=2.4.0",
    "triton>=3.0.0",
    "transformers>=4.51.0",
    "pydantic",
    "ray",
    "flash-attn",
    "xxhash",
    "dlslime>=0.0.1.post9",
    "dlblas"
]

[project.urls]
Homepage="https://github.com/nanodeploy-project/nano-deploy"

[tool.setuptools.packages.find]
where = ["."]
include = ["nanodeploy*"]
