# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class SamplingParams(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SamplingParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSamplingParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # SamplingParams
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SamplingParams
    def Temperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # SamplingParams
    def MaxTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SamplingParams
    def IgnoreEos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(
                self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
            )
        return False


def SamplingParamsStart(builder):
    builder.StartObject(3)


def Start(builder):
    return SamplingParamsStart(builder)


def SamplingParamsAddTemperature(builder, temperature):
    builder.PrependFloat64Slot(0, temperature, 0.0)


def AddTemperature(builder, temperature):
    return SamplingParamsAddTemperature(builder, temperature)


def SamplingParamsAddMaxTokens(builder, maxTokens):
    builder.PrependInt32Slot(1, maxTokens, 0)


def AddMaxTokens(builder, maxTokens):
    return SamplingParamsAddMaxTokens(builder, maxTokens)


def SamplingParamsAddIgnoreEos(builder, ignoreEos):
    builder.PrependBoolSlot(2, ignoreEos, 0)


def AddIgnoreEos(builder, ignoreEos):
    return SamplingParamsAddIgnoreEos(builder, ignoreEos)


def SamplingParamsEnd(builder):
    return builder.EndObject()


def End(builder):
    return SamplingParamsEnd(builder)
