"""Checkpoint validation and full MLA measurements, isolated from serving."""
from pathlib import Path
from types import SimpleNamespace
import json
import torch
import torch.distributed as dist

MODEL = Path('/hgpfs/Kimi-K3')


def setup(worker, tp):
    from torch.distributed.device_mesh import DeviceMesh
    from dlengine.runtime.context.distributed import set_dist_context
    from dlengine.runtime.layers import init_backend
    from dlengine.runtime.models.quant_config import QuantizationConfig
    from dlengine.runtime.models.trait import apply_hf_config_compatibility_fixes
    ctx = set_dist_context(rank=worker.rank, world_size=worker.world,
        attention_dp=worker.world // tp, attention_tp=tp,
        ffn_ep=worker.world, initialize_meshes=False)
    ctx.attn_device_mesh = DeviceMesh.from_group([worker.groups[1], worker.groups[tp]], 'cuda', mesh=torch.arange(worker.rank // tp * tp, (worker.rank // tp + 1) * tp).reshape(1, tp), mesh_dim_names=('attn_sp', 'attn_tp'))
    init_backend(QuantizationConfig(), backend_type='blackwell')
    torch.set_default_dtype(torch.bfloat16)
    raw = json.loads((MODEL / 'config.json').read_text())
    hf = SimpleNamespace(**raw['text_config'])
    apply_hf_config_compatibility_fixes(hf, raw)
    index = json.loads((MODEL / 'model.safetensors.index.json').read_text())['weight_map']
    return hf, index


@torch.inference_mode()
def measure_checkpoint(worker):
    from examples.kimi_k3_fp8_kv_validation import load_attention, validate_attention
    hf, index = setup(worker, 1)
    layers = [i for i, kind in enumerate(hf.layer_types) if kind == 'full_attention']
    rows = []
    for layer in layers[worker.rank::worker.world]:
        torch.manual_seed(2026 + layer)
        attention, norm = load_attention(MODEL, hf, index, layer)
        result = validate_attention(attention, norm, hf, prefill_tokens=129, chunk_tokens=63, decode_steps=4)
        for dtype, value in result.items():
            rows.append(dict(rank=worker.rank, layer=layer, cache_dtype=dtype,
                cache_bytes=value['cache_bytes'],
                prefill_relative_l2=value['prefill']['relative_l2'],
                prefill_cosine=value['prefill']['cosine'],
                decode_relative_l2=value['decode']['relative_l2'],
                decode_cosine=value['decode']['cosine'],
                graph_matches_eager=value['graph_matches_eager'], dummy_preserves_cache=value['dummy_preserves_cache']))
        print(f'Checkpoint rank={worker.rank} MLA layer={layer}: passed', flush=True)
        del attention, norm
        torch.cuda.empty_cache()
    return rows


@torch.inference_mode()
def measure_mla(worker):
    """Complete real-weight MLA including projections/cache write/output reduction.

    Histories are synthetic latents, not generated by a complete K3 model.
    Every request owns distinct physical pages. Long histories are initialized
    from a repeating finite random tile to avoid timing initialization.
    """
    from examples.kimi_k3_fp8_kv_validation import load_attention, allocate_cache, validate_attention
    from dlengine.runtime.context.batch import set_batch_context, reset_batch_context
    import torch.nn.functional as F
    import csv
    outdir = Path(__file__).parent / getattr(worker, 'mla_progress', 'results/gb200_mla_progress')
    outdir.mkdir(exist_ok=True)
    rows = []
    for tp in getattr(worker, "mla_tps", sorted(worker.groups, reverse=True)):
        hf, index = setup(worker, tp)
        torch.manual_seed(1234)
        attention, norm = load_attention(MODEL, hf, index, 3)
        valid = validate_attention(attention, norm, hf, prefill_tokens=129, chunk_tokens=63, decode_steps=4)
        for dtype in ('fp8_e4m3', 'bfloat16'):
            for length in (1024, 8192, 32768, 131072, 524288, 1048576):
                points = [('decode', b, 1) for b in getattr(worker, 'mla_batches', (1, 8, 32))]
                points += [('prefill', 1, c) for c in getattr(worker, 'mla_chunks', (128, 1024, 8192)) if c <= length]
                for phase, batch, chunk in points:
                    pages_per_seq = (length + 63) // 64
                    cache = allocate_cache(hf, dtype, batch * pages_per_seq)
                    # Populate every page; no aliasing between sequences.
                    torch.manual_seed(4567)
                    tile = torch.randn(64, 1, 576, device='cuda', dtype=torch.bfloat16) * 0.1
                    cache.copy_(tile.to(cache.dtype).unsqueeze(0).expand_as(cache))
                    attention.attn_fwd.k_cache = cache
                    bt = torch.arange(batch * pages_per_seq, device='cuda', dtype=torch.int32).reshape(1, batch, pages_per_seq)
                    positions = torch.arange(length - chunk, length, device='cuda', dtype=torch.int64).repeat(batch)
                    slots = torch.arange(batch, device='cuda')[:, None] * pages_per_seq * 64 + torch.arange(length - chunk, length, device='cuda')[None, :]
                    torch.manual_seed(9012)
                    hidden = F.rms_norm(torch.randn(batch * chunk, hf.hidden_size, device='cuda', dtype=torch.bfloat16), (hf.hidden_size,), norm, hf.rms_norm_eps)
                    set_batch_context(is_prefill=phase == 'prefill',
                        cu_seqlens_q=torch.arange(batch + 1, device='cuda', dtype=torch.int32) * chunk,
                        cu_seqlens_k=torch.arange(batch + 1, device='cuda', dtype=torch.int32) * length,
                        max_seqlen_q=chunk, max_seqlen_k=length,
                        context_lens=torch.full((1, batch), length, device='cuda', dtype=torch.int32),
                        block_tables=bt, slot_mapping=slots.flatten().long())
                    op = lambda: attention(positions, hidden)
                    result = op()
                    torch.cuda.synchronize()
                    assert torch.isfinite(result).all().item()
                    baseline = torch.cuda.memory_allocated()
                    torch.cuda.reset_peak_memory_stats()
                    op()
                    torch.cuda.synchronize()
                    peak = torch.cuda.max_memory_allocated() - baseline
                    dist.barrier()
                    eager = [worker.time(op, warmup=1, repeats=3) for _ in range(3)]
                    graph_ms = ''
                    if phase == 'decode':
                        stream = torch.cuda.Stream()
                        stream.wait_stream(torch.cuda.current_stream())
                        with torch.cuda.stream(stream):
                            for _ in range(3): op()
                        stream.synchronize()
                        graph = torch.cuda.CUDAGraph()
                        dist.barrier()
                        with torch.cuda.graph(graph, stream=stream):
                            graph_out = op()
                        dist.barrier()
                        values = [worker.time(graph.replay, warmup=3, repeats=20) for _ in range(3)]
                        graph_ms = sorted(values)[1]
                        torch.testing.assert_close(graph_out, result, rtol=0, atol=0)
                        del graph, graph_out
                    row = dict(rank=worker.rank, world=worker.world, tp=tp, dp=worker.world // tp,
                        phase=phase, cache_dtype=dtype, context=length, batch_per_dp=batch, chunk=chunk,
                        eager_ms=sorted(eager)[1], graph_ms=graph_ms, dynamic_peak_bytes=peak,
                        cache_bytes=cache.untyped_storage().nbytes(),
                        short_reference_relative_l2=valid[dtype][phase]['relative_l2'])
                    rows.append(row)
                    with (outdir / f'rank{worker.rank}.csv').open('w') as stream:
                        writer = csv.DictWriter(stream, fieldnames=row)
                        writer.writeheader(); writer.writerows(rows)
                    if worker.rank == 0: print('MLA', row, flush=True)
                    del result, hidden, cache, tile, bt, slots
                    attention.attn_fwd.k_cache = None
                    reset_batch_context()
                    torch.cuda.empty_cache()
        del attention, norm
        torch.cuda.empty_cache()
    return rows

@torch.inference_mode()
def measure_real_moe(worker):
    """Real checkpoint router + latent/shared/routed FFN on synthetic activations."""
    import re
    import csv
    from safetensors import safe_open
    from torch import nn
    from torch.distributed.device_mesh import DeviceMesh
    from dlengine.runtime.context.distributed import get_dist_context
    from dlengine.runtime.context.batch import set_batch_context
    from dlengine.runtime.layers import init_backend
    from dlengine.runtime.models.kimi_k3.kimi_k3 import KimiMoE
    from dlengine.runtime.models.kimi_k3.kimi_k3_loader import load_weights
    from dlengine.runtime.models.quant_config import QuantizationConfig
    from dlengine.runtime.runner.runner_config import set_runner_config
    import torch.distributed._symmetric_memory as symm_mem
    symm_mem.set_backend('NCCL')
    outdir = Path(__file__).parent / 'results/gb200_real_moe_progress'
    outdir.mkdir(exist_ok=True)
    rows = []
    for ep in (16, 8, 4):
        hf, index = setup(worker, 1)
        ctx = get_dist_context(); ctx.ffn_ep = ep; ctx.ffn_dp = worker.world // ep
        start = worker.rank // ep * ep
        ctx.ffn_device_mesh = DeviceMesh.from_group([worker.groups[ep], worker.groups[1]], 'cuda',
            mesh=torch.arange(start, start + ep).reshape(ep, 1), mesh_dim_names=('ffn_ep', 'ffn_tp'))
        quant = QuantizationConfig(**hf.quantization_config)
        init_backend(quant, backend_type='blackwell')
        set_runner_config(mega_moe_max_tokens_per_rank=2048)
        with torch.device('cuda'): layer = KimiMoE(hf, quant, 1).eval()
        model = nn.Module(); model.config=hf; model.quantization_config=quant
        model.model=nn.Module(); model.model.layers=nn.ModuleDict({'1': nn.Module()})
        model.model.layers['1'].mlp=layer
        selected = {}
        for name, shard in index.items():
            if not name.startswith('language_model.model.layers.1.block_sparse_moe.'): continue
            match = re.search(r'\.experts\.(\d+)\.', name)
            if match and not ctx.ffn_ep_rank * (896 // ep) <= int(match[1]) < (ctx.ffn_ep_rank + 1) * (896 // ep): continue
            selected.setdefault(shard, []).append(name)
        def tensors():
            for shard, names in selected.items():
                with safe_open(MODEL / shard, framework='pt', device='cpu') as f:
                    for name in names: yield name, name, f.get_tensor(name)
        load_weights(model, tensors())
        print(f'Real MoE rank {worker.rank} EP{ep}: loaded {sum(map(len, selected.values()))} tensors', flush=True)
        for total in (16, 128, 2048, 8192, 32768):
            for sources in sorted({ep, min(4, ep), min(8, ep)}):
                if total < sources or total // sources > 2048: continue
                n = total // sources if ctx.ffn_ep_rank < sources else 0
                torch.manual_seed(8234 + ctx.ffn_ep_rank)
                x = torch.randn(n, 7168, device='cuda', dtype=torch.bfloat16)
                set_batch_context(is_prefill=total > 128)
                from dlengine.runtime.kernel.jit.sgl.moe_front import fused_front
                score, ids, latent = fused_front(x, layer.fused_front_weight, layer.e_score_correction_bias,
                    layer.latent, layer.top_k, layer.experts.routed_scaling_factor == 1.)
                counts = torch.bincount(ids.flatten().long(), minlength=896)
                dist.all_reduce(counts, group=worker.groups[ep])
                imbalance = (counts.max().float() / counts.float().mean()).item()
                eager_output = layer(x)
                torch.cuda.synchronize(); assert torch.isfinite(eager_output).all().item()
                baseline=torch.cuda.memory_allocated();torch.cuda.reset_peak_memory_stats()
                layer(x);torch.cuda.synchronize();peak=torch.cuda.max_memory_allocated()-baseline
                dist.barrier()
                eager=[worker.time(lambda: layer(x),warmup=3,repeats=20) for _ in range(3)]
                stream=torch.cuda.Stream();stream.wait_stream(torch.cuda.current_stream())
                with torch.cuda.stream(stream):
                    for _ in range(3): layer(x)
                stream.synchronize();graph=torch.cuda.CUDAGraph();dist.barrier()
                with torch.cuda.graph(graph,stream=stream): graph_out=layer(x)
                dist.barrier()
                values=[worker.time(graph.replay,warmup=3,repeats=20) for _ in range(3)]
                torch.testing.assert_close(graph_out,eager_output,atol=.05,rtol=.03)
                row=dict(rank=worker.rank,ep=ep,ffn_dp=16//ep,total_tokens_per_ep=total,
                    sources=sources,local_rows=n,eager_ms=sorted(eager)[1],graph_ms=sorted(values)[1],
                    expert_max_mean_load=imbalance,dynamic_peak_bytes=peak,
                    weights='checkpoint layer 1',input_distribution='synthetic normal')
                rows.append(row)
                with (outdir/f'rank{worker.rank}.csv').open('w') as f:
                    w=csv.DictWriter(f,fieldnames=row);w.writeheader();w.writerows(rows)
                if worker.rank==0:print('REAL_MOE',row,flush=True)
                del graph,graph_out,eager_output,x,score,ids,latent,counts
        del layer,model
        torch.cuda.empty_cache()
    return rows


def measure_equal_kda(worker):
    from bench.k3_partition.component_kernels import measure_kda
    worker.kda_chunks = ()
    worker.kda_batches = (2, 4, 16, 64)
    return measure_kda(worker)


def measure_equal_mla(worker):
    worker.mla_tps = tuple(sorted(worker.groups, reverse=True))
    worker.mla_progress = 'results/gb200_mla_equal_progress'
    worker.mla_batches = (2, 4, 16)
    worker.mla_chunks = ()
    return measure_mla(worker)


def measure_mla_tp1(worker):
    worker.mla_tps = (1,)
    worker.mla_progress = 'results/gb200_mla_tp1_progress'
    return measure_mla(worker)

@torch.inference_mode()
def measure_cold(worker):
    """Actual sequential cold Prefill of a real-weight MLA layer to the cap."""
    import os
    import csv
    from examples.kimi_k3_fp8_kv_validation import load_attention, allocate_cache
    from dlengine.runtime.context.batch import set_batch_context
    import torch.nn.functional as F
    rows=[]
    for tp in (16, 8, 4):
        hf,index=setup(worker,tp)
        attention,norm=load_attention(MODEL,hf,index,3)
        for dtype in ('bfloat16','fp8_e4m3'):
            for length,chunk in [(8192,8192),(131072,8192),(1048576,8192)] + ([(1048576,4096),(1048576,16384)] if tp==16 else []):
                pages=length//64
                cache=allocate_cache(hf,dtype,pages)
                attention.attn_fwd.k_cache=cache
                bt=torch.arange(pages-1,-1,-1,device='cuda',dtype=torch.int32).reshape(1,1,pages)
                torch.manual_seed(8654)
                hidden=F.rms_norm(torch.randn(chunk,hf.hidden_size,device='cuda',dtype=torch.bfloat16),(hf.hidden_size,),norm,hf.rms_norm_eps)
                def step(start,end):
                    pos=torch.arange(start,end,device='cuda',dtype=torch.int64)
                    slots=bt.flatten()[pos//64].long()*64+pos%64
                    set_batch_context(is_prefill=True,
                        cu_seqlens_q=torch.tensor([0,end-start],device='cuda',dtype=torch.int32),
                        cu_seqlens_k=torch.tensor([0,end],device='cuda',dtype=torch.int32),
                        max_seqlen_q=end-start,max_seqlen_k=end,block_tables=bt,slot_mapping=slots)
                    return attention(pos,hidden[:end-start])
                # Warm kernels outside measurement, then wipe cache. Each timed
                # sweep starts from an empty history and appends every chunk.
                step(0,chunk);torch.cuda.synchronize();cache.zero_()
                dist.barrier();baseline=torch.cuda.memory_allocated();torch.cuda.reset_peak_memory_stats()
                a,b=torch.cuda.Event(enable_timing=True),torch.cuda.Event(enable_timing=True)
                import time
                wall=time.perf_counter();a.record()
                for start in range(0,length,chunk): output=step(start,min(start+chunk,length))
                b.record();b.synchronize();wall=time.perf_counter()-wall
                elapsed=a.elapsed_time(b);peak=torch.cuda.max_memory_allocated()-baseline
                assert torch.isfinite(output).all().item()
                # Bounded and unsplit attention must agree for a nonzero,
                # checkpoint-populated long prefix. Only this last chunk is
                # recomputed; graph timing above is unrelated to this check.
                os.environ['DLENGINE_MLA_PREFIX_CHUNK_SIZE']='0'
                reference=step(length-chunk,length)
                os.environ['DLENGINE_MLA_PREFIX_CHUNK_SIZE']='131072'
                bounded=step(length-chunk,length)
                error=((bounded.float()-reference.float()).norm()/reference.float().norm().clamp_min(1e-12)).item()
                assert error < .02, error
                rows.append(dict(rank=worker.rank,tp=tp,dp=16//tp,context=length,chunk=chunk,
                    cache_dtype=dtype,cold_prefill_cuda_ms=elapsed,cold_prefill_wall_ms=wall*1000,
                    dynamic_peak_bytes=peak,cache_bytes=cache.untyped_storage().nbytes(),
                    split_vs_unsplit_relative_l2=error,weights='MLA layer 3',samples=1))
                if worker.rank==0:print('COLD',rows[-1],flush=True)
                del cache,hidden,output,reference,bounded
                attention.attn_fwd.k_cache=None;torch.cuda.empty_cache()
        del attention,norm
    return rows
