# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class EngineInfo(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EngineInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEngineInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # EngineInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EngineInfo
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EngineInfo
    def Host(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EngineInfo
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EngineInfo
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def EngineInfoStart(builder):
    builder.StartObject(4)


def Start(builder):
    return EngineInfoStart(builder)


def EngineInfoAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0
    )


def AddId(builder, id):
    return EngineInfoAddId(builder, id)


def EngineInfoAddHost(builder, host):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(host), 0
    )


def AddHost(builder, host):
    return EngineInfoAddHost(builder, host)


def EngineInfoAddPort(builder, port):
    builder.PrependInt32Slot(2, port, 0)


def AddPort(builder, port):
    return EngineInfoAddPort(builder, port)


def EngineInfoAddRole(builder, role):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(role), 0
    )


def AddRole(builder, role):
    return EngineInfoAddRole(builder, role)


def EngineInfoEnd(builder):
    return builder.EndObject()


def End(builder):
    return EngineInfoEnd(builder)
