# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class P2PInit(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = P2PInit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsP2PInit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # P2PInit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # P2PInit
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nanodeploy.fbs.EngineInfo import EngineInfo

            obj = EngineInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # P2PInit
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # P2PInit
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def P2PInitStart(builder):
    builder.StartObject(1)


def Start(builder):
    return P2PInitStart(builder)


def P2PInitAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0
    )


def AddNodes(builder, nodes):
    return P2PInitAddNodes(builder, nodes)


def P2PInitStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartNodesVector(builder, numElems):
    return P2PInitStartNodesVector(builder, numElems)


def P2PInitEnd(builder):
    return builder.EndObject()


def End(builder):
    return P2PInitEnd(builder)
