namespace nanodeploy.fbs;

table EngineInfo {
  id: string;
  role: string; // "prefill" or "decode"
  rank: int;
  world_size: int;
  num_blocks: int;
  host: string;
  port: int;
  status: string; // "initializing" or "ready"
}

table EndpointBytes {
  data: [ubyte];
}

table EndpointInfoList {
  endpoints: [EndpointBytes];
}

table Peer {
  remote_id: string;
  remote_info: [EndpointInfoList];
}

table P2PInit {
  nodes: [EngineInfo];
}

table P2PConnect {
  peers: [Peer];
}

table P2PInitResponse {
  responses: [Peer];
}

root_type P2PInit;
