include "../../DLSlime/proto/rdma.fbs";

namespace nanodeploy.fbs;

table EngineInfo {
  id: string;
  role: string; // "prefill" or "decode"
  rank: int;
  world_size: int;
  num_blocks: int;
  host: string;
  port: int;
  status: string; // "initializing" or "ready"
}

table Peer {
  id: string;
  local_info: [ubyte];  // My endpoint info for this peer (RdmaEndpointInfo)
  remote_info: [ubyte]; // Peer's endpoint info for me (RdmaEndpointInfo)
}

table P2PInit {
  nodes: [EngineInfo];
}

table P2PConnect {
  peers: [Peer];
}

table P2PInitResponse {
  responses: [Peer];
}

root_type P2PInit;
