# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlockLocation(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # BlockLocation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlockLocation
    def First(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BlockLocation
    def Second(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateBlockLocation(builder, first, second):
    builder.Prep(4, 8)
    builder.PrependInt32(second)
    builder.PrependInt32(first)
    return builder.Offset()
