# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class P2PConnect(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = P2PConnect()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsP2PConnect(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # P2PConnect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # P2PConnect
    def TargetIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # P2PConnect
    def TargetIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # P2PConnect
    def TargetIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def P2PConnectStart(builder):
    builder.StartObject(1)


def Start(builder):
    return P2PConnectStart(builder)


def P2PConnectAddTargetIds(builder, targetIds):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(targetIds), 0
    )


def AddTargetIds(builder, targetIds):
    return P2PConnectAddTargetIds(builder, targetIds)


def P2PConnectStartTargetIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartTargetIdsVector(builder, numElems):
    return P2PConnectStartTargetIdsVector(builder, numElems)


def P2PConnectEnd(builder):
    return builder.EndObject()


def End(builder):
    return P2PConnectEnd(builder)
