# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class SequenceStatus(object):
    INITIALIZING = 0
    WAITING = 1
    RUNNING_PREFILL = 2
    TO_BE_MIGRATED = 3
    WAITING_MIGRATION = 4
    RUNNING_DECODE = 5
    FINISHED = 6
