# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SequenceList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SequenceList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSequenceList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SequenceList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SequenceList
    def Sequences(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nanodeploy.fbs.Sequence import Sequence
            obj = Sequence()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SequenceList
    def SequencesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SequenceList
    def SequencesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SequenceListStart(builder): builder.StartObject(1)
def Start(builder):
    return SequenceListStart(builder)
def SequenceListAddSequences(builder, sequences): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sequences), 0)
def AddSequences(builder, sequences):
    return SequenceListAddSequences(builder, sequences)
def SequenceListStartSequencesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartSequencesVector(builder, numElems):
    return SequenceListStartSequencesVector(builder, numElems)
def SequenceListEnd(builder): return builder.EndObject()
def End(builder):
    return SequenceListEnd(builder)