// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SEQUENCE_NANODEPLOY_FBS_H_
#define FLATBUFFERS_GENERATED_SEQUENCE_NANODEPLOY_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 && FLATBUFFERS_VERSION_MINOR == 0 && FLATBUFFERS_VERSION_REVISION == 8,
              "Non-compatible flatbuffers version included");

namespace nanodeploy {
namespace fbs {

struct BlockLocation;

struct IntList;
struct IntListBuilder;

struct BlockContext;
struct BlockContextBuilder;

struct SamplingParams;
struct SamplingParamsBuilder;

struct Sequence;
struct SequenceBuilder;

struct SequenceList;
struct SequenceListBuilder;

struct StepOut;
struct StepOutBuilder;

enum SequenceStatus : int8_t {
    SequenceStatus_INITIALIZING      = 0,
    SequenceStatus_WAITING           = 1,
    SequenceStatus_RUNNING_PREFILL   = 2,
    SequenceStatus_TO_BE_MIGRATED    = 3,
    SequenceStatus_WAITING_MIGRATION = 4,
    SequenceStatus_RUNNING_DECODE    = 5,
    SequenceStatus_FINISHED          = 6,
    SequenceStatus_MIN               = SequenceStatus_INITIALIZING,
    SequenceStatus_MAX               = SequenceStatus_FINISHED
};

inline const SequenceStatus (&EnumValuesSequenceStatus())[7]
{
    static const SequenceStatus values[] = {SequenceStatus_INITIALIZING,
                                            SequenceStatus_WAITING,
                                            SequenceStatus_RUNNING_PREFILL,
                                            SequenceStatus_TO_BE_MIGRATED,
                                            SequenceStatus_WAITING_MIGRATION,
                                            SequenceStatus_RUNNING_DECODE,
                                            SequenceStatus_FINISHED};
    return values;
}

inline const char* const* EnumNamesSequenceStatus()
{
    static const char* const names[8] = {"INITIALIZING",
                                         "WAITING",
                                         "RUNNING_PREFILL",
                                         "TO_BE_MIGRATED",
                                         "WAITING_MIGRATION",
                                         "RUNNING_DECODE",
                                         "FINISHED",
                                         nullptr};
    return names;
}

inline const char* EnumNameSequenceStatus(SequenceStatus e)
{
    if (flatbuffers::IsOutRange(e, SequenceStatus_INITIALIZING, SequenceStatus_FINISHED))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesSequenceStatus()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BlockLocation FLATBUFFERS_FINAL_CLASS
{
private:
    int32_t first_;
    int32_t second_;

public:
    BlockLocation(): first_(0), second_(0) {}
    BlockLocation(int32_t _first, int32_t _second):
        first_(flatbuffers::EndianScalar(_first)), second_(flatbuffers::EndianScalar(_second))
    {
    }
    int32_t first() const
    {
        return flatbuffers::EndianScalar(first_);
    }
    int32_t second() const
    {
        return flatbuffers::EndianScalar(second_);
    }
};
FLATBUFFERS_STRUCT_END(BlockLocation, 8);

struct IntList FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef IntListBuilder       Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_VALUES = 4
    };
    const flatbuffers::Vector<int32_t>* values() const
    {
        return GetPointer<const flatbuffers::Vector<int32_t>*>(VT_VALUES);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_VALUES) && verifier.VerifyVector(values())
               && verifier.EndTable();
    }
};

struct IntListBuilder {
    typedef IntList                 Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_values(flatbuffers::Offset<flatbuffers::Vector<int32_t>> values)
    {
        fbb_.AddOffset(IntList::VT_VALUES, values);
    }
    explicit IntListBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<IntList> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<IntList>(end);
        return o;
    }
};

inline flatbuffers::Offset<IntList> CreateIntList(flatbuffers::FlatBufferBuilder&                   _fbb,
                                                  flatbuffers::Offset<flatbuffers::Vector<int32_t>> values = 0)
{
    IntListBuilder builder_(_fbb);
    builder_.add_values(values);
    return builder_.Finish();
}

inline flatbuffers::Offset<IntList> CreateIntListDirect(flatbuffers::FlatBufferBuilder& _fbb,
                                                        const std::vector<int32_t>*     values = nullptr)
{
    auto values__ = values ? _fbb.CreateVector<int32_t>(*values) : 0;
    return nanodeploy::fbs::CreateIntList(_fbb, values__);
}

struct BlockContext FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef BlockContextBuilder  Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ENGINE_ID             = 4,
        VT_DP_IDX                = 6,
        VT_MASTER_SP_IDX         = 8,
        VT_ATTENTION_SP          = 10,
        VT_ATTENTION_DP          = 12,
        VT_BLOCK_LOCATION        = 14,
        VT_NUM_DISPATCHED_TOKENS = 16,
        VT_SP_BLOCK_TABLE        = 18
    };
    const flatbuffers::String* engine_id() const
    {
        return GetPointer<const flatbuffers::String*>(VT_ENGINE_ID);
    }
    int32_t dp_idx() const
    {
        return GetField<int32_t>(VT_DP_IDX, 0);
    }
    int32_t master_sp_idx() const
    {
        return GetField<int32_t>(VT_MASTER_SP_IDX, 0);
    }
    int32_t attention_sp() const
    {
        return GetField<int32_t>(VT_ATTENTION_SP, 0);
    }
    int32_t attention_dp() const
    {
        return GetField<int32_t>(VT_ATTENTION_DP, 0);
    }
    const flatbuffers::Vector<const nanodeploy::fbs::BlockLocation*>* block_location() const
    {
        return GetPointer<const flatbuffers::Vector<const nanodeploy::fbs::BlockLocation*>*>(VT_BLOCK_LOCATION);
    }
    const flatbuffers::Vector<int32_t>* num_dispatched_tokens() const
    {
        return GetPointer<const flatbuffers::Vector<int32_t>*>(VT_NUM_DISPATCHED_TOKENS);
    }
    const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::IntList>>* sp_block_table() const
    {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::IntList>>*>(VT_SP_BLOCK_TABLE);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_ENGINE_ID) && verifier.VerifyString(engine_id())
               && VerifyField<int32_t>(verifier, VT_DP_IDX, 4) && VerifyField<int32_t>(verifier, VT_MASTER_SP_IDX, 4)
               && VerifyField<int32_t>(verifier, VT_ATTENTION_SP, 4)
               && VerifyField<int32_t>(verifier, VT_ATTENTION_DP, 4) && VerifyOffset(verifier, VT_BLOCK_LOCATION)
               && verifier.VerifyVector(block_location()) && VerifyOffset(verifier, VT_NUM_DISPATCHED_TOKENS)
               && verifier.VerifyVector(num_dispatched_tokens()) && VerifyOffset(verifier, VT_SP_BLOCK_TABLE)
               && verifier.VerifyVector(sp_block_table()) && verifier.VerifyVectorOfTables(sp_block_table())
               && verifier.EndTable();
    }
};

struct BlockContextBuilder {
    typedef BlockContext            Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_engine_id(flatbuffers::Offset<flatbuffers::String> engine_id)
    {
        fbb_.AddOffset(BlockContext::VT_ENGINE_ID, engine_id);
    }
    void add_dp_idx(int32_t dp_idx)
    {
        fbb_.AddElement<int32_t>(BlockContext::VT_DP_IDX, dp_idx, 0);
    }
    void add_master_sp_idx(int32_t master_sp_idx)
    {
        fbb_.AddElement<int32_t>(BlockContext::VT_MASTER_SP_IDX, master_sp_idx, 0);
    }
    void add_attention_sp(int32_t attention_sp)
    {
        fbb_.AddElement<int32_t>(BlockContext::VT_ATTENTION_SP, attention_sp, 0);
    }
    void add_attention_dp(int32_t attention_dp)
    {
        fbb_.AddElement<int32_t>(BlockContext::VT_ATTENTION_DP, attention_dp, 0);
    }
    void
    add_block_location(flatbuffers::Offset<flatbuffers::Vector<const nanodeploy::fbs::BlockLocation*>> block_location)
    {
        fbb_.AddOffset(BlockContext::VT_BLOCK_LOCATION, block_location);
    }
    void add_num_dispatched_tokens(flatbuffers::Offset<flatbuffers::Vector<int32_t>> num_dispatched_tokens)
    {
        fbb_.AddOffset(BlockContext::VT_NUM_DISPATCHED_TOKENS, num_dispatched_tokens);
    }
    void add_sp_block_table(
        flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::IntList>>> sp_block_table)
    {
        fbb_.AddOffset(BlockContext::VT_SP_BLOCK_TABLE, sp_block_table);
    }
    explicit BlockContextBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<BlockContext> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<BlockContext>(end);
        return o;
    }
};

inline flatbuffers::Offset<BlockContext> CreateBlockContext(
    flatbuffers::FlatBufferBuilder&                                                         _fbb,
    flatbuffers::Offset<flatbuffers::String>                                                engine_id             = 0,
    int32_t                                                                                 dp_idx                = 0,
    int32_t                                                                                 master_sp_idx         = 0,
    int32_t                                                                                 attention_sp          = 0,
    int32_t                                                                                 attention_dp          = 0,
    flatbuffers::Offset<flatbuffers::Vector<const nanodeploy::fbs::BlockLocation*>>         block_location        = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>>                                       num_dispatched_tokens = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::IntList>>> sp_block_table        = 0)
{
    BlockContextBuilder builder_(_fbb);
    builder_.add_sp_block_table(sp_block_table);
    builder_.add_num_dispatched_tokens(num_dispatched_tokens);
    builder_.add_block_location(block_location);
    builder_.add_attention_dp(attention_dp);
    builder_.add_attention_sp(attention_sp);
    builder_.add_master_sp_idx(master_sp_idx);
    builder_.add_dp_idx(dp_idx);
    builder_.add_engine_id(engine_id);
    return builder_.Finish();
}

inline flatbuffers::Offset<BlockContext>
CreateBlockContextDirect(flatbuffers::FlatBufferBuilder&                    _fbb,
                         const char*                                        engine_id                     = nullptr,
                         int32_t                                            dp_idx                        = 0,
                         int32_t                                            master_sp_idx                 = 0,
                         int32_t                                            attention_sp                  = 0,
                         int32_t                                            attention_dp                  = 0,
                         const std::vector<nanodeploy::fbs::BlockLocation>* block_location                = nullptr,
                         const std::vector<int32_t>*                        num_dispatched_tokens         = nullptr,
                         const std::vector<flatbuffers::Offset<nanodeploy::fbs::IntList>>* sp_block_table = nullptr)
{
    auto engine_id__ = engine_id ? _fbb.CreateString(engine_id) : 0;
    auto block_location__ =
        block_location ? _fbb.CreateVectorOfStructs<nanodeploy::fbs::BlockLocation>(*block_location) : 0;
    auto num_dispatched_tokens__ = num_dispatched_tokens ? _fbb.CreateVector<int32_t>(*num_dispatched_tokens) : 0;
    auto sp_block_table__ =
        sp_block_table ? _fbb.CreateVector<flatbuffers::Offset<nanodeploy::fbs::IntList>>(*sp_block_table) : 0;
    return nanodeploy::fbs::CreateBlockContext(_fbb,
                                               engine_id__,
                                               dp_idx,
                                               master_sp_idx,
                                               attention_sp,
                                               attention_dp,
                                               block_location__,
                                               num_dispatched_tokens__,
                                               sp_block_table__);
}

struct SamplingParams FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef SamplingParamsBuilder Builder;
    enum FlatBuffersVTableOffset  FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_TEMPERATURE = 4,
        VT_MAX_TOKENS  = 6,
        VT_IGNORE_EOS  = 8
    };
    double temperature() const
    {
        return GetField<double>(VT_TEMPERATURE, 0.0);
    }
    int32_t max_tokens() const
    {
        return GetField<int32_t>(VT_MAX_TOKENS, 0);
    }
    bool ignore_eos() const
    {
        return GetField<uint8_t>(VT_IGNORE_EOS, 0) != 0;
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyField<double>(verifier, VT_TEMPERATURE, 8)
               && VerifyField<int32_t>(verifier, VT_MAX_TOKENS, 4) && VerifyField<uint8_t>(verifier, VT_IGNORE_EOS, 1)
               && verifier.EndTable();
    }
};

struct SamplingParamsBuilder {
    typedef SamplingParams          Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_temperature(double temperature)
    {
        fbb_.AddElement<double>(SamplingParams::VT_TEMPERATURE, temperature, 0.0);
    }
    void add_max_tokens(int32_t max_tokens)
    {
        fbb_.AddElement<int32_t>(SamplingParams::VT_MAX_TOKENS, max_tokens, 0);
    }
    void add_ignore_eos(bool ignore_eos)
    {
        fbb_.AddElement<uint8_t>(SamplingParams::VT_IGNORE_EOS, static_cast<uint8_t>(ignore_eos), 0);
    }
    explicit SamplingParamsBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<SamplingParams> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<SamplingParams>(end);
        return o;
    }
};

inline flatbuffers::Offset<SamplingParams> CreateSamplingParams(flatbuffers::FlatBufferBuilder& _fbb,
                                                                double                          temperature = 0.0,
                                                                int32_t                         max_tokens  = 0,
                                                                bool                            ignore_eos  = false)
{
    SamplingParamsBuilder builder_(_fbb);
    builder_.add_temperature(temperature);
    builder_.add_max_tokens(max_tokens);
    builder_.add_ignore_eos(ignore_eos);
    return builder_.Finish();
}

struct Sequence FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef SequenceBuilder      Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SEQ_ID                  = 4,
        VT_STATUS                  = 6,
        VT_SAMPLING_PARAMS         = 8,
        VT_LAST_TOKEN              = 10,
        VT_NUM_TOKENS              = 12,
        VT_NUM_PROMPT_TOKENS       = 14,
        VT_NUM_CHECKPOINTED_TOKENS = 16,
        VT_NUM_CACHED_TOKENS       = 18,
        VT_TOKEN_IDS               = 20,
        VT_SLOTS                   = 22
    };
    uint64_t seq_id() const
    {
        return GetField<uint64_t>(VT_SEQ_ID, 0);
    }
    nanodeploy::fbs::SequenceStatus status() const
    {
        return static_cast<nanodeploy::fbs::SequenceStatus>(GetField<int8_t>(VT_STATUS, 0));
    }
    const nanodeploy::fbs::SamplingParams* sampling_params() const
    {
        return GetPointer<const nanodeploy::fbs::SamplingParams*>(VT_SAMPLING_PARAMS);
    }
    int32_t last_token() const
    {
        return GetField<int32_t>(VT_LAST_TOKEN, 0);
    }
    int32_t num_tokens() const
    {
        return GetField<int32_t>(VT_NUM_TOKENS, 0);
    }
    int32_t num_prompt_tokens() const
    {
        return GetField<int32_t>(VT_NUM_PROMPT_TOKENS, 0);
    }
    int32_t num_checkpointed_tokens() const
    {
        return GetField<int32_t>(VT_NUM_CHECKPOINTED_TOKENS, 0);
    }
    int32_t num_cached_tokens() const
    {
        return GetField<int32_t>(VT_NUM_CACHED_TOKENS, 0);
    }
    const flatbuffers::Vector<int32_t>* token_ids() const
    {
        return GetPointer<const flatbuffers::Vector<int32_t>*>(VT_TOKEN_IDS);
    }
    const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>* slots() const
    {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>*>(VT_SLOTS);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_SEQ_ID, 8)
               && VerifyField<int8_t>(verifier, VT_STATUS, 1) && VerifyOffset(verifier, VT_SAMPLING_PARAMS)
               && verifier.VerifyTable(sampling_params()) && VerifyField<int32_t>(verifier, VT_LAST_TOKEN, 4)
               && VerifyField<int32_t>(verifier, VT_NUM_TOKENS, 4)
               && VerifyField<int32_t>(verifier, VT_NUM_PROMPT_TOKENS, 4)
               && VerifyField<int32_t>(verifier, VT_NUM_CHECKPOINTED_TOKENS, 4)
               && VerifyField<int32_t>(verifier, VT_NUM_CACHED_TOKENS, 4) && VerifyOffset(verifier, VT_TOKEN_IDS)
               && verifier.VerifyVector(token_ids()) && VerifyOffset(verifier, VT_SLOTS)
               && verifier.VerifyVector(slots()) && verifier.VerifyVectorOfTables(slots()) && verifier.EndTable();
    }
};

struct SequenceBuilder {
    typedef Sequence                Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_seq_id(uint64_t seq_id)
    {
        fbb_.AddElement<uint64_t>(Sequence::VT_SEQ_ID, seq_id, 0);
    }
    void add_status(nanodeploy::fbs::SequenceStatus status)
    {
        fbb_.AddElement<int8_t>(Sequence::VT_STATUS, static_cast<int8_t>(status), 0);
    }
    void add_sampling_params(flatbuffers::Offset<nanodeploy::fbs::SamplingParams> sampling_params)
    {
        fbb_.AddOffset(Sequence::VT_SAMPLING_PARAMS, sampling_params);
    }
    void add_last_token(int32_t last_token)
    {
        fbb_.AddElement<int32_t>(Sequence::VT_LAST_TOKEN, last_token, 0);
    }
    void add_num_tokens(int32_t num_tokens)
    {
        fbb_.AddElement<int32_t>(Sequence::VT_NUM_TOKENS, num_tokens, 0);
    }
    void add_num_prompt_tokens(int32_t num_prompt_tokens)
    {
        fbb_.AddElement<int32_t>(Sequence::VT_NUM_PROMPT_TOKENS, num_prompt_tokens, 0);
    }
    void add_num_checkpointed_tokens(int32_t num_checkpointed_tokens)
    {
        fbb_.AddElement<int32_t>(Sequence::VT_NUM_CHECKPOINTED_TOKENS, num_checkpointed_tokens, 0);
    }
    void add_num_cached_tokens(int32_t num_cached_tokens)
    {
        fbb_.AddElement<int32_t>(Sequence::VT_NUM_CACHED_TOKENS, num_cached_tokens, 0);
    }
    void add_token_ids(flatbuffers::Offset<flatbuffers::Vector<int32_t>> token_ids)
    {
        fbb_.AddOffset(Sequence::VT_TOKEN_IDS, token_ids);
    }
    void add_slots(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>> slots)
    {
        fbb_.AddOffset(Sequence::VT_SLOTS, slots);
    }
    explicit SequenceBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<Sequence> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<Sequence>(end);
        return o;
    }
};

inline flatbuffers::Offset<Sequence>
CreateSequence(flatbuffers::FlatBufferBuilder& _fbb,
               uint64_t                        seq_id = 0,
               nanodeploy::fbs::SequenceStatus status = nanodeploy::fbs::SequenceStatus_INITIALIZING,
               flatbuffers::Offset<nanodeploy::fbs::SamplingParams> sampling_params                               = 0,
               int32_t                                              last_token                                    = 0,
               int32_t                                              num_tokens                                    = 0,
               int32_t                                              num_prompt_tokens                             = 0,
               int32_t                                              num_checkpointed_tokens                       = 0,
               int32_t                                              num_cached_tokens                             = 0,
               flatbuffers::Offset<flatbuffers::Vector<int32_t>>    token_ids                                     = 0,
               flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>> slots = 0)
{
    SequenceBuilder builder_(_fbb);
    builder_.add_seq_id(seq_id);
    builder_.add_slots(slots);
    builder_.add_token_ids(token_ids);
    builder_.add_num_cached_tokens(num_cached_tokens);
    builder_.add_num_checkpointed_tokens(num_checkpointed_tokens);
    builder_.add_num_prompt_tokens(num_prompt_tokens);
    builder_.add_num_tokens(num_tokens);
    builder_.add_last_token(last_token);
    builder_.add_sampling_params(sampling_params);
    builder_.add_status(status);
    return builder_.Finish();
}

inline flatbuffers::Offset<Sequence>
CreateSequenceDirect(flatbuffers::FlatBufferBuilder& _fbb,
                     uint64_t                        seq_id = 0,
                     nanodeploy::fbs::SequenceStatus status = nanodeploy::fbs::SequenceStatus_INITIALIZING,
                     flatbuffers::Offset<nanodeploy::fbs::SamplingParams>                   sampling_params         = 0,
                     int32_t                                                                last_token              = 0,
                     int32_t                                                                num_tokens              = 0,
                     int32_t                                                                num_prompt_tokens       = 0,
                     int32_t                                                                num_checkpointed_tokens = 0,
                     int32_t                                                                num_cached_tokens       = 0,
                     const std::vector<int32_t>*                                            token_ids = nullptr,
                     const std::vector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>* slots     = nullptr)
{
    auto token_ids__ = token_ids ? _fbb.CreateVector<int32_t>(*token_ids) : 0;
    auto slots__     = slots ? _fbb.CreateVector<flatbuffers::Offset<nanodeploy::fbs::BlockContext>>(*slots) : 0;
    return nanodeploy::fbs::CreateSequence(_fbb,
                                           seq_id,
                                           status,
                                           sampling_params,
                                           last_token,
                                           num_tokens,
                                           num_prompt_tokens,
                                           num_checkpointed_tokens,
                                           num_cached_tokens,
                                           token_ids__,
                                           slots__);
}

struct SequenceList FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef SequenceListBuilder  Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SEQUENCES = 4
    };
    const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>* sequences() const
    {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>*>(VT_SEQUENCES);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_SEQUENCES) && verifier.VerifyVector(sequences())
               && verifier.VerifyVectorOfTables(sequences()) && verifier.EndTable();
    }
};

struct SequenceListBuilder {
    typedef SequenceList            Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void
    add_sequences(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>> sequences)
    {
        fbb_.AddOffset(SequenceList::VT_SEQUENCES, sequences);
    }
    explicit SequenceListBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<SequenceList> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<SequenceList>(end);
        return o;
    }
};

inline flatbuffers::Offset<SequenceList> CreateSequenceList(
    flatbuffers::FlatBufferBuilder&                                                          _fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>> sequences = 0)
{
    SequenceListBuilder builder_(_fbb);
    builder_.add_sequences(sequences);
    return builder_.Finish();
}

inline flatbuffers::Offset<SequenceList>
CreateSequenceListDirect(flatbuffers::FlatBufferBuilder&                                    _fbb,
                         const std::vector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>* sequences = nullptr)
{
    auto sequences__ = sequences ? _fbb.CreateVector<flatbuffers::Offset<nanodeploy::fbs::Sequence>>(*sequences) : 0;
    return nanodeploy::fbs::CreateSequenceList(_fbb, sequences__);
}

struct StepOut FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef StepOutBuilder       Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SEQ_ID   = 4,
        VT_TOKEN_ID = 6,
        VT_STATUS   = 8
    };
    uint64_t seq_id() const
    {
        return GetField<uint64_t>(VT_SEQ_ID, 0);
    }
    uint32_t token_id() const
    {
        return GetField<uint32_t>(VT_TOKEN_ID, 0);
    }
    nanodeploy::fbs::SequenceStatus status() const
    {
        return static_cast<nanodeploy::fbs::SequenceStatus>(GetField<int8_t>(VT_STATUS, 0));
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_SEQ_ID, 8)
               && VerifyField<uint32_t>(verifier, VT_TOKEN_ID, 4) && VerifyField<int8_t>(verifier, VT_STATUS, 1)
               && verifier.EndTable();
    }
};

struct StepOutBuilder {
    typedef StepOut                 Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_seq_id(uint64_t seq_id)
    {
        fbb_.AddElement<uint64_t>(StepOut::VT_SEQ_ID, seq_id, 0);
    }
    void add_token_id(uint32_t token_id)
    {
        fbb_.AddElement<uint32_t>(StepOut::VT_TOKEN_ID, token_id, 0);
    }
    void add_status(nanodeploy::fbs::SequenceStatus status)
    {
        fbb_.AddElement<int8_t>(StepOut::VT_STATUS, static_cast<int8_t>(status), 0);
    }
    explicit StepOutBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<StepOut> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<StepOut>(end);
        return o;
    }
};

inline flatbuffers::Offset<StepOut>
CreateStepOut(flatbuffers::FlatBufferBuilder& _fbb,
              uint64_t                        seq_id   = 0,
              uint32_t                        token_id = 0,
              nanodeploy::fbs::SequenceStatus status   = nanodeploy::fbs::SequenceStatus_INITIALIZING)
{
    StepOutBuilder builder_(_fbb);
    builder_.add_seq_id(seq_id);
    builder_.add_token_id(token_id);
    builder_.add_status(status);
    return builder_.Finish();
}

inline const nanodeploy::fbs::SequenceList* GetSequenceList(const void* buf)
{
    return flatbuffers::GetRoot<nanodeploy::fbs::SequenceList>(buf);
}

inline const nanodeploy::fbs::SequenceList* GetSizePrefixedSequenceList(const void* buf)
{
    return flatbuffers::GetSizePrefixedRoot<nanodeploy::fbs::SequenceList>(buf);
}

inline bool VerifySequenceListBuffer(flatbuffers::Verifier& verifier)
{
    return verifier.VerifyBuffer<nanodeploy::fbs::SequenceList>(nullptr);
}

inline bool VerifySizePrefixedSequenceListBuffer(flatbuffers::Verifier& verifier)
{
    return verifier.VerifySizePrefixedBuffer<nanodeploy::fbs::SequenceList>(nullptr);
}

inline void FinishSequenceListBuffer(flatbuffers::FlatBufferBuilder&                    fbb,
                                     flatbuffers::Offset<nanodeploy::fbs::SequenceList> root)
{
    fbb.Finish(root);
}

inline void FinishSizePrefixedSequenceListBuffer(flatbuffers::FlatBufferBuilder&                    fbb,
                                                 flatbuffers::Offset<nanodeploy::fbs::SequenceList> root)
{
    fbb.FinishSizePrefixed(root);
}

}  // namespace fbs
}  // namespace nanodeploy

#endif  // FLATBUFFERS_GENERATED_SEQUENCE_NANODEPLOY_FBS_H_
