# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class Sequence(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Sequence()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSequence(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # Sequence
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sequence
    def SeqId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # Sequence
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def Temperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # Sequence
    def MaxTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def IgnoreEos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(
                self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
            )
        return False

    # Sequence
    def LastToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def NumTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def NumPromptTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def NumCheckpointedTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def NumCachedTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def TokenIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Int32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Sequence
    def TokenIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Sequence
    def TokenIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Sequence
    def TokenIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Sequence
    def Slots(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nanodeploy.fbs.BlockContext import BlockContext

            obj = BlockContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Sequence
    def SlotsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Sequence
    def SlotsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0


def SequenceStart(builder):
    builder.StartObject(12)


def Start(builder):
    return SequenceStart(builder)


def SequenceAddSeqId(builder, seqId):
    builder.PrependUint64Slot(0, seqId, 0)


def AddSeqId(builder, seqId):
    return SequenceAddSeqId(builder, seqId)


def SequenceAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)


def AddStatus(builder, status):
    return SequenceAddStatus(builder, status)


def SequenceAddTemperature(builder, temperature):
    builder.PrependFloat64Slot(2, temperature, 0.0)


def AddTemperature(builder, temperature):
    return SequenceAddTemperature(builder, temperature)


def SequenceAddMaxTokens(builder, maxTokens):
    builder.PrependInt32Slot(3, maxTokens, 0)


def AddMaxTokens(builder, maxTokens):
    return SequenceAddMaxTokens(builder, maxTokens)


def SequenceAddIgnoreEos(builder, ignoreEos):
    builder.PrependBoolSlot(4, ignoreEos, 0)


def AddIgnoreEos(builder, ignoreEos):
    return SequenceAddIgnoreEos(builder, ignoreEos)


def SequenceAddLastToken(builder, lastToken):
    builder.PrependInt32Slot(5, lastToken, 0)


def AddLastToken(builder, lastToken):
    return SequenceAddLastToken(builder, lastToken)


def SequenceAddNumTokens(builder, numTokens):
    builder.PrependInt32Slot(6, numTokens, 0)


def AddNumTokens(builder, numTokens):
    return SequenceAddNumTokens(builder, numTokens)


def SequenceAddNumPromptTokens(builder, numPromptTokens):
    builder.PrependInt32Slot(7, numPromptTokens, 0)


def AddNumPromptTokens(builder, numPromptTokens):
    return SequenceAddNumPromptTokens(builder, numPromptTokens)


def SequenceAddNumCheckpointedTokens(builder, numCheckpointedTokens):
    builder.PrependInt32Slot(8, numCheckpointedTokens, 0)


def AddNumCheckpointedTokens(builder, numCheckpointedTokens):
    return SequenceAddNumCheckpointedTokens(builder, numCheckpointedTokens)


def SequenceAddNumCachedTokens(builder, numCachedTokens):
    builder.PrependInt32Slot(9, numCachedTokens, 0)


def AddNumCachedTokens(builder, numCachedTokens):
    return SequenceAddNumCachedTokens(builder, numCachedTokens)


def SequenceAddTokenIds(builder, tokenIds):
    builder.PrependUOffsetTRelativeSlot(
        10, flatbuffers.number_types.UOffsetTFlags.py_type(tokenIds), 0
    )


def AddTokenIds(builder, tokenIds):
    return SequenceAddTokenIds(builder, tokenIds)


def SequenceStartTokenIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartTokenIdsVector(builder, numElems):
    return SequenceStartTokenIdsVector(builder, numElems)


def SequenceAddSlots(builder, slots):
    builder.PrependUOffsetTRelativeSlot(
        11, flatbuffers.number_types.UOffsetTFlags.py_type(slots), 0
    )


def AddSlots(builder, slots):
    return SequenceAddSlots(builder, slots)


def SequenceStartSlotsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartSlotsVector(builder, numElems):
    return SequenceStartSlotsVector(builder, numElems)


def SequenceEnd(builder):
    return builder.EndObject()


def End(builder):
    return SequenceEnd(builder)
