[server]
host = "0.0.0.0"
port = 3000
model_name = "Proxima-7B"

# Engine Connection
engine_host = "127.0.0.1"
engine_port = 5000

[tokenizer]
path = "/home/majinming/models/qwen3-0.6b-local/tokenizer.json"

[engine]
mode = "Disaggregated"

[[engine.prefill]]
host = "127.0.0.1"
port = 6001

[[engine.decode]]
host = "127.0.0.1"
port = 6002

[scheduler]
queue_size = 1000
timeout_ms = 30000
