# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine_rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'engine_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65ngine_rpc.proto\x12\nnanodeploy\"?\n\x0cStreamPacket\x12\x0e\n\x06seq_id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x32S\n\rEngineService\x12\x42\n\x08Interact\x12\x18.nanodeploy.StreamPacket\x1a\x18.nanodeploy.StreamPacket(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMPACKET']._serialized_start=32
  _globals['_STREAMPACKET']._serialized_end=95
  _globals['_ENGINESERVICE']._serialized_start=97
  _globals['_ENGINESERVICE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
