// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CONNECTION_NANODEPLOY_FBS_H_
#define FLATBUFFERS_GENERATED_CONNECTION_NANODEPLOY_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 && FLATBUFFERS_VERSION_MINOR == 0 && FLATBUFFERS_VERSION_REVISION == 8,
              "Non-compatible flatbuffers version included");

namespace nanodeploy {
namespace fbs {

struct EngineInfo;
struct EngineInfoBuilder;

struct P2PInit;
struct P2PInitBuilder;

struct P2PConnect;
struct P2PConnectBuilder;

struct EngineInfo FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef EngineInfoBuilder    Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ID   = 4,
        VT_HOST = 6,
        VT_PORT = 8,
        VT_ROLE = 10
    };
    const flatbuffers::String* id() const
    {
        return GetPointer<const flatbuffers::String*>(VT_ID);
    }
    const flatbuffers::String* host() const
    {
        return GetPointer<const flatbuffers::String*>(VT_HOST);
    }
    int32_t port() const
    {
        return GetField<int32_t>(VT_PORT, 0);
    }
    const flatbuffers::String* role() const
    {
        return GetPointer<const flatbuffers::String*>(VT_ROLE);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_ID) && verifier.VerifyString(id())
               && VerifyOffset(verifier, VT_HOST) && verifier.VerifyString(host())
               && VerifyField<int32_t>(verifier, VT_PORT, 4) && VerifyOffset(verifier, VT_ROLE)
               && verifier.VerifyString(role()) && verifier.EndTable();
    }
};

struct EngineInfoBuilder {
    typedef EngineInfo              Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void                            add_id(flatbuffers::Offset<flatbuffers::String> id)
    {
        fbb_.AddOffset(EngineInfo::VT_ID, id);
    }
    void add_host(flatbuffers::Offset<flatbuffers::String> host)
    {
        fbb_.AddOffset(EngineInfo::VT_HOST, host);
    }
    void add_port(int32_t port)
    {
        fbb_.AddElement<int32_t>(EngineInfo::VT_PORT, port, 0);
    }
    void add_role(flatbuffers::Offset<flatbuffers::String> role)
    {
        fbb_.AddOffset(EngineInfo::VT_ROLE, role);
    }
    explicit EngineInfoBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<EngineInfo> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<EngineInfo>(end);
        return o;
    }
};

inline flatbuffers::Offset<EngineInfo> CreateEngineInfo(flatbuffers::FlatBufferBuilder&          _fbb,
                                                        flatbuffers::Offset<flatbuffers::String> id   = 0,
                                                        flatbuffers::Offset<flatbuffers::String> host = 0,
                                                        int32_t                                  port = 0,
                                                        flatbuffers::Offset<flatbuffers::String> role = 0)
{
    EngineInfoBuilder builder_(_fbb);
    builder_.add_role(role);
    builder_.add_port(port);
    builder_.add_host(host);
    builder_.add_id(id);
    return builder_.Finish();
}

inline flatbuffers::Offset<EngineInfo> CreateEngineInfoDirect(flatbuffers::FlatBufferBuilder& _fbb,
                                                              const char*                     id   = nullptr,
                                                              const char*                     host = nullptr,
                                                              int32_t                         port = 0,
                                                              const char*                     role = nullptr)
{
    auto id__   = id ? _fbb.CreateString(id) : 0;
    auto host__ = host ? _fbb.CreateString(host) : 0;
    auto role__ = role ? _fbb.CreateString(role) : 0;
    return nanodeploy::fbs::CreateEngineInfo(_fbb, id__, host__, port, role__);
}

struct P2PInit FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef P2PInitBuilder       Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_NODES = 4
    };
    const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>* nodes() const
    {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>*>(VT_NODES);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_NODES) && verifier.VerifyVector(nodes())
               && verifier.VerifyVectorOfTables(nodes()) && verifier.EndTable();
    }
};

struct P2PInitBuilder {
    typedef P2PInit                 Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void add_nodes(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>> nodes)
    {
        fbb_.AddOffset(P2PInit::VT_NODES, nodes);
    }
    explicit P2PInitBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<P2PInit> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<P2PInit>(end);
        return o;
    }
};

inline flatbuffers::Offset<P2PInit>
CreateP2PInit(flatbuffers::FlatBufferBuilder&                                                            _fbb,
              flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>> nodes = 0)
{
    P2PInitBuilder builder_(_fbb);
    builder_.add_nodes(nodes);
    return builder_.Finish();
}

inline flatbuffers::Offset<P2PInit>
CreateP2PInitDirect(flatbuffers::FlatBufferBuilder&                                      _fbb,
                    const std::vector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>* nodes = nullptr)
{
    auto nodes__ = nodes ? _fbb.CreateVector<flatbuffers::Offset<nanodeploy::fbs::EngineInfo>>(*nodes) : 0;
    return nanodeploy::fbs::CreateP2PInit(_fbb, nodes__);
}

struct P2PConnect FLATBUFFERS_FINAL_CLASS: private flatbuffers::Table {
    typedef P2PConnectBuilder    Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_TARGET_IDS = 4
    };
    const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>* target_ids() const
    {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>*>(VT_TARGET_IDS);
    }
    bool Verify(flatbuffers::Verifier& verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_TARGET_IDS)
               && verifier.VerifyVector(target_ids()) && verifier.VerifyVectorOfStrings(target_ids())
               && verifier.EndTable();
    }
};

struct P2PConnectBuilder {
    typedef P2PConnect              Table;
    flatbuffers::FlatBufferBuilder& fbb_;
    flatbuffers::uoffset_t          start_;
    void add_target_ids(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> target_ids)
    {
        fbb_.AddOffset(P2PConnect::VT_TARGET_IDS, target_ids);
    }
    explicit P2PConnectBuilder(flatbuffers::FlatBufferBuilder& _fbb): fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<P2PConnect> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto       o   = flatbuffers::Offset<P2PConnect>(end);
        return o;
    }
};

inline flatbuffers::Offset<P2PConnect>
CreateP2PConnect(flatbuffers::FlatBufferBuilder&                                                    _fbb,
                 flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> target_ids = 0)
{
    P2PConnectBuilder builder_(_fbb);
    builder_.add_target_ids(target_ids);
    return builder_.Finish();
}

inline flatbuffers::Offset<P2PConnect>
CreateP2PConnectDirect(flatbuffers::FlatBufferBuilder&                              _fbb,
                       const std::vector<flatbuffers::Offset<flatbuffers::String>>* target_ids = nullptr)
{
    auto target_ids__ = target_ids ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*target_ids) : 0;
    return nanodeploy::fbs::CreateP2PConnect(_fbb, target_ids__);
}

inline const nanodeploy::fbs::P2PInit* GetP2PInit(const void* buf)
{
    return flatbuffers::GetRoot<nanodeploy::fbs::P2PInit>(buf);
}

inline const nanodeploy::fbs::P2PInit* GetSizePrefixedP2PInit(const void* buf)
{
    return flatbuffers::GetSizePrefixedRoot<nanodeploy::fbs::P2PInit>(buf);
}

inline bool VerifyP2PInitBuffer(flatbuffers::Verifier& verifier)
{
    return verifier.VerifyBuffer<nanodeploy::fbs::P2PInit>(nullptr);
}

inline bool VerifySizePrefixedP2PInitBuffer(flatbuffers::Verifier& verifier)
{
    return verifier.VerifySizePrefixedBuffer<nanodeploy::fbs::P2PInit>(nullptr);
}

inline void FinishP2PInitBuffer(flatbuffers::FlatBufferBuilder& fbb, flatbuffers::Offset<nanodeploy::fbs::P2PInit> root)
{
    fbb.Finish(root);
}

inline void FinishSizePrefixedP2PInitBuffer(flatbuffers::FlatBufferBuilder&               fbb,
                                            flatbuffers::Offset<nanodeploy::fbs::P2PInit> root)
{
    fbb.FinishSizePrefixed(root);
}

}  // namespace fbs
}  // namespace nanodeploy

#endif  // FLATBUFFERS_GENERATED_CONNECTION_NANODEPLOY_FBS_H_
