import os

# Default values
DEFAULT_MODEL_PATH = "/home/majinming/models/Qwen3-30B-A3B-Instruct-2507"
DEFAULT_SERVER_URL = "http://localhost:3000/chat"
DEFAULT_MAX_TOKENS = 1024
DEFAULT_SYSTEM_PROMPT = ""

MODEL_PATH = os.getenv("MODEL_PATH", DEFAULT_MODEL_PATH)
SERVER_URL = os.getenv("SERVER_URL", DEFAULT_SERVER_URL)
MAX_TOKENS = int(os.getenv("MAX_TOKENS", DEFAULT_MAX_TOKENS))
SYSTEM_PROMPT = os.getenv("SYSTEM_PROMPT", DEFAULT_SYSTEM_PROMPT)
